/**
 * This file was generated by the JPA Modeler
 */ 

package org.ohdsi.webapi.study;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */

@Entity
@Table(name="STUDY_COHORTSET")
public class CohortSet { 

    @Id
    @GeneratedValue(generator="COHORT_SET_SEQ",strategy=GenerationType.SEQUENCE)
    @SequenceGenerator(name="COHORT_SET_SEQ",sequenceName="COHORT_SET_SEQ",allocationSize=1)
    private Integer id;

    @Basic
    private String name;

    @Basic
    private String description;

    @OneToMany(targetEntity = StudyCohort.class)
    @JoinTable(name="STUDY_COHORTSET_XREF",joinColumns={@JoinColumn(name="COHORTSET_ID",referencedColumnName="ID")},inverseJoinColumns={@JoinColumn(name="COHORT_ID",referencedColumnName="ID")})
    private List<StudyCohort> cohortList;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }


    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


    public List<StudyCohort> getCohortList() {
        return this.cohortList;
    }

    public void setCohortList(List<StudyCohort> cohortList) {
        this.cohortList = cohortList;
    }


}
