/**
 * This file was generated by the JPA Modeler
 */ 

package org.ohdsi.webapi.study;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */

@Embeddable
public class CohortRelationship implements Serializable { 

    @Column(name="RELATIONSHIP_TYPE")
    @Basic
    private RelationshipType relationshipType;

    @OneToOne(optional=false,targetEntity = StudyCohort.class)
    @JoinColumn(name="COHORT_2_ID",referencedColumnName="ID")
    private StudyCohort target;


    public RelationshipType getRelationshipType() {
        return this.relationshipType;
    }

    public void setRelationshipType(RelationshipType relationshipType) {
        this.relationshipType = relationshipType;
    }

    public StudyCohort getTarget() {
        return this.target;
    }

    public void setTarget(StudyCohort target) {
        this.target = target;
    }


}
