//
// This file was generated by the JPA Modeler
//
package org.ohdsi.webapi.study;

import java.io.Serializable;



public class CohortRelationshipPK implements Serializable {

    private Integer cohort_1;

    private Integer cohort_2;

    private Integer study;

    public CohortRelationshipPK(){
    }

    public CohortRelationshipPK(Integer cohort_1,Integer cohort_2,Integer study){
        this.cohort_1=cohort_1;
        this.cohort_2=cohort_2;
        this.study=study;
    }


   public Integer getCohort_1() {
        return this.cohort_1;
    }

    public void setCohort_1 (Integer cohort_1) {
        this.cohort_1 = cohort_1;
    }

   public Integer getCohort_2() {
        return this.cohort_2;
    }

    public void setCohort_2 (Integer cohort_2) {
        this.cohort_2 = cohort_2;
    }

   public Integer getStudy() {
        return this.study;
    }

    public void setStudy (Integer study) {
        this.study = study;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {return false;}
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {return false;}
        final CohortRelationshipPK other = (CohortRelationshipPK) obj;
        if (!java.util.Objects.equals(this.getCohort_1(), other.getCohort_1())) {        return false;        }
        if (!java.util.Objects.equals(this.getCohort_2(), other.getCohort_2())) {        return false;        }
        if (!java.util.Objects.equals(this.getStudy(), other.getStudy())) {        return false;        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 89 * hash + (this.getCohort_1() != null ? this.getCohort_1().hashCode() : 0);
        hash = 89 * hash + (this.getCohort_2() != null ? this.getCohort_2().hashCode() : 0);
        hash = 89 * hash + (this.getStudy() != null ? this.getStudy().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "CohortRelationshipPK{" + " cohort_1=" + cohort_1 + ", cohort_2=" + cohort_2 + ", study=" + study + '}';
    }

}
