/**
 * This file was generated by the JPA Modeler
 */ 

package org.ohdsi.webapi.study;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */

@Embeddable
public class Concept { 

    @Column(name="CONCEPT_ID")
    @Basic
    private long conceptId;

    @Column(name="CONCEPT_NAME")
    @Basic
    private String conceptName;

    public long getConceptId() {
        return this.conceptId;
    }

    public void setConceptId(long conceptId) {
        this.conceptId = conceptId;
    }


    public String getConceptName() {
        return this.conceptName;
    }

    public void setConceptName(String conceptName) {
        this.conceptName = conceptName;
    }


}
