/**
 * This file was generated by the JPA Modeler
 */ 

package org.ohdsi.webapi.study;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */

@Entity
@Table(name="STUDY_SOURCE")
public class StudySource { 

    @Id
    private Integer id;


    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


}
