/**
 * This file was generated by the JPA Modeler
 */
package org.ohdsi.webapi.study;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */
@Entity
@Table(name = "STUDY_IR")
public class StudyIR {

	@Id
	@GeneratedValue(generator = "STUDY_IR_SEQ", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "STUDY_IR_SEQ", sequenceName = "STUDY_IR_SEQ", allocationSize = 1)
	private Integer id;

	@Basic
	private String params;

	@OneToMany(fetch = FetchType.LAZY, targetEntity = StudyCohort.class)
	@JoinTable(name = "STUDY_IR_T", joinColumns = {
		@JoinColumn(name = "ANALYSIS_ID", referencedColumnName = "ID")}, inverseJoinColumns = {
		@JoinColumn(name = "COHORT_ID", referencedColumnName = "ID")})
	private List<StudyCohort> targets;

	@OneToMany(fetch = FetchType.LAZY, targetEntity = StudyCohort.class)
	@JoinTable(name = "STUDY_IR_O", joinColumns = {
		@JoinColumn(name = "ANALYSIS_ID", referencedColumnName = "ID")}, inverseJoinColumns = {
		@JoinColumn(name = "COHORT_ID", referencedColumnName = "ID")})
	private List<StudyCohort> outcomes;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getParams() {
		return this.params;
	}

	public void setParams(String params) {
		this.params = params;
	}

	public List<StudyCohort> getTargets() {
		return this.targets;
	}

	public void setTargets(List<StudyCohort> targets) {
		this.targets = targets;
	}

	public List<StudyCohort> getOutcomes() {
		return this.outcomes;
	}

	public void setOutcomes(List<StudyCohort> outcomes) {
		this.outcomes = outcomes;
	}

}
