/**
 * This file was generated by the JPA Modeler
 */ 

package org.ohdsi.webapi.study;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */

@Entity
@Table(name="STUDY_CCA")
public class StudyCCA { 

    @Id
    @GeneratedValue(generator="STUDY_CCA_SEQ",strategy=GenerationType.SEQUENCE)
    @SequenceGenerator(name="STUDY_CCA_SEQ",sequenceName="STUDY_CCA_SEQ",allocationSize=1)
    private Integer id;

    @Basic
    private String params;

    @OneToMany(cascade={CascadeType.ALL},targetEntity = StudyCCAPair.class)
    @JoinTable(name="CCA_PAIR_XREF",joinColumns={@JoinColumn(name="CCA_ID",referencedColumnName="ID")},inverseJoinColumns={@JoinColumn(name="TARGET_ID",referencedColumnName="TARGET_ID"),@JoinColumn(name="COMPARATOR_ID",referencedColumnName="COMPARATOR_ID"),@JoinColumn(name="OUTCOME_ID",referencedColumnName="OUTCOME_ID")})
    private List<StudyCCAPair> studyCCAPairs;


    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getParams() {
        return this.params;
    }

    public void setParams(String params) {
        this.params = params;
    }

    public List<StudyCCAPair> getStudyCCAPairs() {
        return this.studyCCAPairs;
    }

    public void setStudyCCAPairs(List<StudyCCAPair> studyCCAPairs) {
        this.studyCCAPairs = studyCCAPairs;
    }


}
