/**
 * This file was generated by the JPA Modeler
 */
package org.ohdsi.webapi.study;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */
@Entity
@Table(name = "STUDY_SCC")
public class StudySCC {

	@Id
	@GeneratedValue(generator = "STUDY_SCC_SEQ", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "STUDY_SCC_SEQ", sequenceName = "STUDY_SCC_SEQ", allocationSize = 1)
	private Integer id;

	@Column(columnDefinition = "VARCHAR(MAX)")
	@Basic
	private String params;

	@OneToMany(cascade = {CascadeType.ALL}, fetch = FetchType.LAZY, targetEntity = StudySCCPair.class, mappedBy = "ssc")
	private List<StudySCCPair> pairs = new java.util.ArrayList<>();

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getParams() {
		return this.params;
	}

	public void setParams(String params) {
		this.params = params;
	}

	public List<StudySCCPair> getPairs() {
		return this.pairs;
	}

	public void setPairs(List<StudySCCPair> pairs) {
		this.pairs = pairs;
	}

}
