//
// This file was generated by the JPA Modeler
//
package org.ohdsi.webapi.study;

import java.io.Serializable;



public class StudyCCAPairPK implements Serializable {

    private Integer target;

    private Integer comparator;

    private Integer outcome;

    private Integer cca;

    public StudyCCAPairPK(){
    }

    public StudyCCAPairPK(Integer target,Integer comparator,Integer outcome,Integer cca){
        this.target=target;
        this.comparator=comparator;
        this.outcome=outcome;
        this.cca=cca;
    }


   public Integer getTarget() {
        return this.target;
    }

    public void setTarget (Integer target) {
        this.target = target;
    }

   public Integer getComparator() {
        return this.comparator;
    }

    public void setComparator (Integer comparator) {
        this.comparator = comparator;
    }

   public Integer getOutcome() {
        return this.outcome;
    }

    public void setOutcome (Integer outcome) {
        this.outcome = outcome;
    }

   public Integer getCca() {
        return this.cca;
    }

    public void setCca (Integer cca) {
        this.cca = cca;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {return false;}
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {return false;}
        final StudyCCAPairPK other = (StudyCCAPairPK) obj;
        if (!java.util.Objects.equals(this.getTarget(), other.getTarget())) {        return false;        }
        if (!java.util.Objects.equals(this.getComparator(), other.getComparator())) {        return false;        }
        if (!java.util.Objects.equals(this.getOutcome(), other.getOutcome())) {        return false;        }
        if (!java.util.Objects.equals(this.getCca(), other.getCca())) {        return false;        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + (this.getTarget() != null ? this.getTarget().hashCode() : 0);
        hash = 17 * hash + (this.getComparator() != null ? this.getComparator().hashCode() : 0);
        hash = 17 * hash + (this.getOutcome() != null ? this.getOutcome().hashCode() : 0);
        hash = 17 * hash + (this.getCca() != null ? this.getCca().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "StudyCCAPairPK{" + " target=" + target + ", comparator=" + comparator + ", outcome=" + outcome + ", cca=" + cca + '}';
    }

}
