/**
 * This file was generated by the JPA Modeler
 */ 

package org.ohdsi.webapi.study;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */

@Entity
@Table(name="STUDY")
public class Study { 

    @Id
    @GeneratedValue(generator="STUDY_SEQ",strategy=GenerationType.SEQUENCE)
    @SequenceGenerator(name="STUDY_SEQ",sequenceName="STUDY_SEQ",allocationSize=1)
    private Integer id;

    @Basic(optional=false)
    private String name;

    @Basic
    private String description;

    @Embedded
    private StudyConfig studyConfig;

    @OneToMany(fetch = FetchType.LAZY,targetEntity = StudySource.class)
    @JoinTable(name="STUDY_SOURCE_XREF",joinColumns={@JoinColumn(name="STUDY_ID",referencedColumnName="ID")},inverseJoinColumns={@JoinColumn(name="SOURCE_ID",referencedColumnName="ID")})
    private List<StudySource> sourceList = new java.util.ArrayList<StudySource>();

    @OneToMany(fetch = FetchType.LAZY,targetEntity = StudyIR.class)
    @JoinTable(name="STUDY_IR_XREF",joinColumns={@JoinColumn(name="STUDY_ID",referencedColumnName="ID")},inverseJoinColumns={@JoinColumn(name="IR_ID",referencedColumnName="ID")})
    private List<StudyIR> irAnalysisList = new java.util.ArrayList<StudyIR>();

    @OneToMany(fetch = FetchType.LAZY,targetEntity = StudyCCA.class)
    @JoinTable(name="STUDY_CCA_XREF",joinColumns={@JoinColumn(name="STUDY_ID",referencedColumnName="ID")},inverseJoinColumns={@JoinColumn(name="CCA_ID",referencedColumnName="ID")})
    private List<StudyCCA> ccaList = new java.util.ArrayList<StudyCCA>();

    @OneToMany(fetch = FetchType.LAZY,targetEntity = StudySCC.class)
    @JoinTable(name="STUDY_SCC_XREF",joinColumns={@JoinColumn(name="STUDY_ID",referencedColumnName="ID")},inverseJoinColumns={@JoinColumn(name="SCC_ID",referencedColumnName="ID")})
    private List<StudySCC> sccList = new java.util.ArrayList<>();

    @OneToMany(fetch = FetchType.LAZY,targetEntity = StudyCohort.class)
    @JoinTable(name="STUDY_COHORT_XREF",joinColumns={@JoinColumn(name="STUDY_ID",referencedColumnName="ID")},inverseJoinColumns={@JoinColumn(name="COHORT_ID",referencedColumnName="ID")})
    private List<StudyCohort> cohortList = new java.util.ArrayList<StudyCohort>();

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }


    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


    public StudyConfig getStudyConfig() {
        return this.studyConfig;
    }

    public void setStudyConfig(StudyConfig studyConfig) {
        this.studyConfig = studyConfig;
    }


    public List<StudySource> getSourceList() {
        return this.sourceList;
    }

    public void setSourceList(List<StudySource> sourceList) {
        this.sourceList = sourceList;
    }


    public List<StudyIR> getIrAnalysisList() {
        return this.irAnalysisList;
    }

    public void setIrAnalysisList(List<StudyIR> irAnalysisList) {
        this.irAnalysisList = irAnalysisList;
    }


    public List<StudyCCA> getCcaList() {
        return this.ccaList;
    }

    public void setCcaList(List<StudyCCA> ccaList) {
        this.ccaList = ccaList;
    }


    public List<StudySCC> getSccList() {
        return this.sccList;
    }

    public void setSccList(List<StudySCC> sccList) {
        this.sccList = sccList;
    }


    public List<StudyCohort> getCohortList() {
        return this.cohortList;
    }

    public void setCohortList(List<StudyCohort> cohortList) {
        this.cohortList = cohortList;
    }


}
