/**
 * This file was generated by the JPA Modeler
 */ 

package org.ohdsi.webapi.study;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */

@Entity
@Table(name="STUDY_SCC_PAIR")
@IdClass(StudySCCPairPK.class)
public class StudySCCPair { 

    @Id@OneToOne(targetEntity = StudyCohort.class)
    @JoinColumn(name="TARGET_ID",referencedColumnName="ID")
    private StudyCohort target;

    @Id@OneToOne(targetEntity = StudyCohort.class)
    @JoinColumn(name="OUTCOME_ID",referencedColumnName="ID")
    private StudyCohort outcome;

    @Id@ManyToOne(targetEntity = StudySCC.class)
    @JoinColumn(name="SCC_ID",referencedColumnName="ID")
    private StudySCC ssc;

    @OneToMany(fetch = FetchType.LAZY,targetEntity = StudyCohort.class)
    @JoinTable(name="STUDY_SCC_NEG_CONTROL_XREF",joinColumns={@JoinColumn(name="TARGET_ID",referencedColumnName="TARGET_ID"),@JoinColumn(name="OUTCOME_ID",referencedColumnName="OUTCOME_ID"),@JoinColumn(name="SCC_ID",referencedColumnName="SCC_ID")},inverseJoinColumns={@JoinColumn(name="CONTROL_ID",referencedColumnName="ID")})
    private List<StudyCohort> negativeControls = new java.util.ArrayList<>();


    public StudyCohort getTarget() {
        return this.target;
    }

    public void setTarget(StudyCohort target) {
        this.target = target;
    }

    public StudyCohort getOutcome() {
        return this.outcome;
    }

    public void setOutcome(StudyCohort outcome) {
        this.outcome = outcome;
    }

    public StudySCC getSsc() {
        return this.ssc;
    }

    public void setSsc(StudySCC ssc) {
        this.ssc = ssc;
    }

    public List<StudyCohort> getNegativeControls() {
        return this.negativeControls;
    }

    public void setNegativeControls(List<StudyCohort> negativeControls) {
        this.negativeControls = negativeControls;
    }


}
