/**
 * This file was generated by the JPA Modeler
 */ 

package org.ohdsi.webapi.study.report;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import org.ohdsi.webapi.study.StudySource;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */

@Embeddable
public class ReportSource { 

    @Column(name="IS_ACTIVE",columnDefinition="BIT")
    @Basic
    private boolean active;

    @OneToOne(targetEntity = StudySource.class)
    @JoinColumn(name="SOURCE_ID",referencedColumnName="ID")
    private StudySource source;


    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public StudySource getSource() {
        return this.source;
    }

    public void setSource(StudySource source) {
        this.source = source;
    }


}
