/**
 * This file was generated by the JPA Modeler
 */ 

package org.ohdsi.webapi.study.report;

import javax.persistence.Basic;
import javax.persistence.Embeddable;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */

@Embeddable
public class ReportCovariate { 

    @Basic
    private String covariateId;

    @Basic
    private String covariateName;

    @Basic
    private String ordinal;


    public String getCovariateId() {
        return this.covariateId;
    }

    public void setCovariateId(String covariateId) {
        this.covariateId = covariateId;
    }

    public String getCovariateName() {
        return this.covariateName;
    }

    public void setCovariateName(String covariateName) {
        this.covariateName = covariateName;
    }

    public String getOrdinal() {
        return this.ordinal;
    }

    public void setOrdinal(String ordinal) {
        this.ordinal = ordinal;
    }


}
