/**
 * This file was generated by the JPA Modeler
 */ 

package org.ohdsi.webapi.study.report;

import java.util.List;
import javax.persistence.CollectionTable;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.ohdsi.webapi.study.Study;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */

@Entity
@Table(name="REPORT")
public class Report { 

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;

    @ElementCollection(fetch=FetchType.LAZY)
    private List<ReportCovariate> covariates;

    @ElementCollection(fetch=FetchType.LAZY)
    private List<ReportText> content;

    @ElementCollection(fetch=FetchType.LAZY)
    @CollectionTable(name="REPORT_STATS")
    private List<ReportStats> covariteStats;

    @ElementCollection(fetch=FetchType.LAZY)
    @CollectionTable(name="REPORT_STATS_DIST")
    private List<ReportStatsDist> covariteDists;

    @ElementCollection(fetch=FetchType.LAZY)
    @CollectionTable(name="REPORT_TARGET_XREF",joinColumns={@JoinColumn(name="REPORT_ID",referencedColumnName="ID")})
    private List<ReportCohort> targets;

    @ElementCollection(fetch=FetchType.LAZY)
    @CollectionTable(name="REPORT_OUTCOME_XREF",joinColumns={@JoinColumn(name="REPORT_ID",referencedColumnName="ID")})
    private List<ReportCohort> outcomes;

    @ElementCollection(fetch=FetchType.LAZY)
    @CollectionTable(name="REPORT_SOURCE_XREF")
    private List<ReportSource> sources;

    @ManyToOne(fetch = FetchType.LAZY,targetEntity = Study.class)
    @JoinTable(name="REPORT_STUDY_XREF",joinColumns={@JoinColumn(name="REPORT_ID",referencedColumnName="ID")},inverseJoinColumns={@JoinColumn(name="STUDY_ID",referencedColumnName="ID")})
    private Study study;


    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public List<ReportCovariate> getCovariates() {
        return this.covariates;
    }

    public void setCovariates(List<ReportCovariate> covariates) {
        this.covariates = covariates;
    }

    public List<ReportText> getContent() {
        return this.content;
    }

    public void setContent(List<ReportText> content) {
        this.content = content;
    }

    public List<ReportStats> getCovariteStats() {
        return this.covariteStats;
    }

    public void setCovariteStats(List<ReportStats> covariteStats) {
        this.covariteStats = covariteStats;
    }

    public List<ReportStatsDist> getCovariteDists() {
        return this.covariteDists;
    }

    public void setCovariteDists(List<ReportStatsDist> covariteDists) {
        this.covariteDists = covariteDists;
    }

    public List<ReportCohort> getTargets() {
        return this.targets;
    }

    public void setTargets(List<ReportCohort> targets) {
        this.targets = targets;
    }

    public List<ReportCohort> getOutcomes() {
        return this.outcomes;
    }

    public void setOutcomes(List<ReportCohort> outcomes) {
        this.outcomes = outcomes;
    }

    public List<ReportSource> getSources() {
        return this.sources;
    }

    public void setSources(List<ReportSource> sources) {
        this.sources = sources;
    }

    public Study getStudy() {
        return this.study;
    }

    public void setStudy(Study study) {
        this.study = study;
    }


}
