/**
 * This file was generated by the JPA Modeler
 */ 

package org.ohdsi.webapi.study.report;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import org.ohdsi.webapi.study.StudyCohort;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */

@Embeddable
public class ReportCohortPair { 

    @Column(name="IS_ACTIVE",columnDefinition="BIT")
    @Basic
    private boolean active;

    @OneToOne(optional=false,fetch = FetchType.LAZY,targetEntity = StudyCohort.class)
    @JoinColumn(name="TARGET_COHORT_ID",referencedColumnName="ID")
    private StudyCohort target;

    @OneToOne(optional=false,fetch = FetchType.LAZY,targetEntity = StudyCohort.class)
    @JoinColumn(name="OUTCOME_COHORT_ID",referencedColumnName="ID")
    private StudyCohort outcome;


    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public StudyCohort getTarget() {
        return this.target;
    }

    public void setTarget(StudyCohort target) {
        this.target = target;
    }

    public StudyCohort getOutcome() {
        return this.outcome;
    }

    public void setOutcome(StudyCohort outcome) {
        this.outcome = outcome;
    }


}
