/**
 * This file was generated by the JPA Modeler
 */ 

package org.ohdsi.webapi.study.report;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */

@Embeddable
public class ReportText { 

    @Column(name="SECTION_ID")
    @Basic
    private String sectionId;

    @Basic
    private String content;


    public String getSectionId() {
        return this.sectionId;
    }

    public void setSectionId(String sectionId) {
        this.sectionId = sectionId;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }


}
