/**
 * This file was generated by the JPA Modeler
 */
package org.ohdsi.webapi.study.report;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Lob;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */
@Embeddable
public class ReportContent {

	@Column(name = "SECTION_ID", columnDefinition = "VARCHAR(20)", updatable = false)
	@Basic
	private ContentSection section;

	@Column(name = "CONTENT", columnDefinition = "VARCHAR(MAX)")
	@Lob
	@Basic
	private String content;

	public ContentSection getSection() {
		return this.section;
	}

	public void setSection(ContentSection section) {
		this.section = section;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
