/**
 * This file was generated by the JPA Modeler
 */ 

package org.ohdsi.webapi.study.report;

import javax.persistence.Basic;
import javax.persistence.Embeddable;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */

@Embeddable
public class ReportStatsDist { 

    @Basic
    private String covariateId;

    @Basic
    private String covariateName;

    @Basic
    private String analysisId;

    @Basic
    private String analysisName;

    @Basic
    private String domainId;

    @Basic
    private String timeWindow;

    @Basic
    private String conceptId;

    @Basic
    private String countValue;

    @Basic
    private String minValue;

    @Basic
    private String maxValue;

    @Basic
    private String avgValue;

    @Basic
    private String stdDevValue;

    @Basic
    private String medianValue;

    @Basic
    private String p10Value;

    @Basic
    private String p25Value;

    @Basic
    private String p75Value;

    @Basic
    private String p90Value;


    public String getCovariateId() {
        return this.covariateId;
    }

    public void setCovariateId(String covariateId) {
        this.covariateId = covariateId;
    }

    public String getCovariateName() {
        return this.covariateName;
    }

    public void setCovariateName(String covariateName) {
        this.covariateName = covariateName;
    }

    public String getAnalysisId() {
        return this.analysisId;
    }

    public void setAnalysisId(String analysisId) {
        this.analysisId = analysisId;
    }

    public String getAnalysisName() {
        return this.analysisName;
    }

    public void setAnalysisName(String analysisName) {
        this.analysisName = analysisName;
    }

    public String getDomainId() {
        return this.domainId;
    }

    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    public String getTimeWindow() {
        return this.timeWindow;
    }

    public void setTimeWindow(String timeWindow) {
        this.timeWindow = timeWindow;
    }

    public String getConceptId() {
        return this.conceptId;
    }

    public void setConceptId(String conceptId) {
        this.conceptId = conceptId;
    }

    public String getCountValue() {
        return this.countValue;
    }

    public void setCountValue(String countValue) {
        this.countValue = countValue;
    }

    public String getMinValue() {
        return this.minValue;
    }

    public void setMinValue(String minValue) {
        this.minValue = minValue;
    }

    public String getMaxValue() {
        return this.maxValue;
    }

    public void setMaxValue(String maxValue) {
        this.maxValue = maxValue;
    }

    public String getAvgValue() {
        return this.avgValue;
    }

    public void setAvgValue(String avgValue) {
        this.avgValue = avgValue;
    }

    public String getStdDevValue() {
        return this.stdDevValue;
    }

    public void setStdDevValue(String stdDevValue) {
        this.stdDevValue = stdDevValue;
    }

    public String getMedianValue() {
        return this.medianValue;
    }

    public void setMedianValue(String medianValue) {
        this.medianValue = medianValue;
    }

    public String getP10Value() {
        return this.p10Value;
    }

    public void setP10Value(String p10Value) {
        this.p10Value = p10Value;
    }

    public String getP25Value() {
        return this.p25Value;
    }

    public void setP25Value(String p25Value) {
        this.p25Value = p25Value;
    }

    public String getP75Value() {
        return this.p75Value;
    }

    public void setP75Value(String p75Value) {
        this.p75Value = p75Value;
    }

    public String getP90Value() {
        return this.p90Value;
    }

    public void setP90Value(String p90Value) {
        this.p90Value = p90Value;
    }


}
