/**
 * This file was generated by the JPA Modeler
 */ 

package org.ohdsi.webapi.study.report;

import javax.persistence.Basic;
import javax.persistence.Embeddable;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */

@Embeddable
public class ReportStats { 

    @Basic
    private String covariateId;

    @Basic
    private String covariateName;

    @Basic
    private String analysisId;

    @Basic
    private String analysisName;

    @Basic
    private String domainId;

    @Basic
    private String timeWindow;

    @Basic
    private String conceptId;

    @Basic
    private String countValue;

    @Basic
    private String statValue;


    public String getCovariateId() {
        return this.covariateId;
    }

    public void setCovariateId(String covariateId) {
        this.covariateId = covariateId;
    }

    public String getCovariateName() {
        return this.covariateName;
    }

    public void setCovariateName(String covariateName) {
        this.covariateName = covariateName;
    }

    public String getAnalysisId() {
        return this.analysisId;
    }

    public void setAnalysisId(String analysisId) {
        this.analysisId = analysisId;
    }

    public String getAnalysisName() {
        return this.analysisName;
    }

    public void setAnalysisName(String analysisName) {
        this.analysisName = analysisName;
    }

    public String getDomainId() {
        return this.domainId;
    }

    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    public String getTimeWindow() {
        return this.timeWindow;
    }

    public void setTimeWindow(String timeWindow) {
        this.timeWindow = timeWindow;
    }

    public String getConceptId() {
        return this.conceptId;
    }

    public void setConceptId(String conceptId) {
        this.conceptId = conceptId;
    }

    public String getCountValue() {
        return this.countValue;
    }

    public void setCountValue(String countValue) {
        this.countValue = countValue;
    }

    public String getStatValue() {
        return this.statValue;
    }

    public void setStatValue(String statValue) {
        this.statValue = statValue;
    }


}
