/**
 * This file was generated by the JPA Modeler
 */
package org.ohdsi.webapi.study.report;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * @author Chris Knoll <cknoll@ohdsi.org>
 */
@Embeddable
public class ReportCovariate {

	@Column(name = "COVARIATE_ID")
	@Basic
	private Long covariateId;

	@Column(name = "COVARIATE_NAME", columnDefinition = "VARCHAR(1000)")
	@Basic
	private String covariateName;

	@Column(name = "COVARIATE_SECTION", columnDefinition = "VARCHAR(20)")
	@Basic
	private CovariateSection covariateSection;

	public Long getCovariateId() {
		return this.covariateId;
	}

	public void setCovariateId(Long covariateId) {
		this.covariateId = covariateId;
	}

	public String getCovariateName() {
		return this.covariateName;
	}

	public void setCovariateName(String covariateName) {
		this.covariateName = covariateName;
	}

	public CovariateSection getCovariateSection() {
		return this.covariateSection;
	}

	public void setCovariateSection(CovariateSection covariateSection) {
		this.covariateSection = covariateSection;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}
		if (!java.util.Objects.equals(getClass(), obj.getClass())) {
			return false;
		}
		final ReportCovariate other = (ReportCovariate) obj;
		if (!java.util.Objects.equals(this.getCovariateId(), other.getCovariateId())) {
			return false;
		}
		if (!java.util.Objects.equals(this.getCovariateSection(), other.getCovariateSection())) {
			return false;
		}
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 5;
		hash = 67 * hash + (this.getCovariateId() != null ? this.getCovariateId().hashCode() : 0);
		hash = 67 * hash + (this.getCovariateSection() != null ? this.getCovariateSection().hashCode() : 0);
		return hash;
	}

}
