CREATE TABLE ${ohdsiSchema}.plp
(
  plp_id number(10) NOT NULL,
  name varchar2(255),
  treatment_id number(10) NOT NULL,
  outcome_id number(10) NOT NULL,
  model_type varchar2(255) NOT NULL,
  time_at_risk_start number(10) NOT NULL,
  time_at_risk_end number(10) NOT NULL,
  add_exposure_days_to_end number(10) NOT NULL,
  minimum_washout_period number(10) NOT NULL,
  minimum_days_at_risk number(10) NOT NULL,
  require_time_at_risk number(10) NOT NULL,
  minimum_time_at_risk number(10) NOT NULL,
  sample number(10) NOT NULL,
  sample_size number(10) NOT NULL,
  first_exposure_only number(10) NOT NULL,
  include_all_outcomes number(10) NOT NULL,
  rm_prior_outcomes number(10) NOT NULL,
  prior_outcome_lookback number(10) NOT NULL,
  test_split number(10) NOT NULL,
  test_fraction varchar2(255) NULL,
  n_fold varchar2(255) NULL,
  mo_alpha varchar2(255) NULL,
  mo_class_weight varchar2(255) NULL,
  mo_index_folder varchar2(255) NULL,
  mo_k varchar2(255) NULL,
  mo_learn_rate varchar2(255) NULL,
  mo_learning_rate varchar2(255) NULL,
  mo_max_depth varchar2(255) NULL,
  mo_min_impurity_split varchar2(255) NULL,
  mo_min_rows varchar2(255) NULL,
  mo_min_samples_leaf varchar2(255) NULL,
  mo_min_samples_split varchar2(255) NULL,
  mo_mtries varchar2(255) NULL,
  mo_nestimators varchar2(255) NULL,
  mo_nthread varchar2(255) NULL,
  mo_ntrees varchar2(255) NULL,
  mo_plot varchar2(255) NULL,
  mo_seed varchar2(255) NULL,
  mo_size varchar2(255) NULL,
  mo_variance varchar2(255) NULL,
  mo_var_imp varchar2(255) NULL,
  cv_exclusion_id number(10) NOT NULL,
  cv_inclusion_id number(10) NOT NULL,
  cv_demographics number(10) NOT NULL,
  cv_demographics_gender number(10) NOT NULL,
  cv_demographics_race number(10) NOT NULL,
  cv_demographics_ethnicity number(10) NOT NULL,
  cv_demographics_age number(10) NOT NULL,
  cv_demographics_year number(10) NOT NULL,
  cv_demographics_month number(10) NOT NULL,
  cv_condition_occ number(10) NOT NULL,
  cv_condition_occ_365d number(10) NOT NULL,
  cv_condition_occ_30d number(10) NOT NULL,
  cv_condition_occ_inpt180d number(10) NOT NULL,
  cv_condition_era number(10) NOT NULL,
  cv_condition_era_ever number(10) NOT NULL,
  cv_condition_era_overlap number(10) NOT NULL,
  cv_condition_group number(10) NOT NULL,
  cv_condition_group_meddra number(10) NOT NULL,
  cv_condition_group_snomed number(10) NOT NULL,
  cv_drug_exposure number(10) NOT NULL,
  cv_drug_exposure_365d number(10) NOT NULL,
  cv_drug_exposure_30d number(10) NOT NULL,
  cv_drug_era number(10) NOT NULL,
  cv_drug_era_365d number(10) NOT NULL,
  cv_drug_era_30d number(10) NOT NULL,
  cv_drug_era_overlap number(10) NOT NULL,
  cv_drug_era_ever number(10) NOT NULL,
  cv_drug_group number(10) NOT NULL,
  cv_procedure_occ number(10) NOT NULL,
  cv_procedure_occ_365d number(10) NOT NULL,
  cv_procedure_occ_30d number(10) NOT NULL,
  cv_procedure_group number(10) NOT NULL,
  cv_observation number(10) NOT NULL,
  cv_observation_365d number(10) NOT NULL,
  cv_observation_30d number(10) NOT NULL,
  cv_observation_count_365d number(10) NOT NULL,
  cv_measurement number(10) NOT NULL,
  cv_measurement_365d number(10) NOT NULL,
  cv_measurement_30d number(10) NOT NULL,
  cv_measurement_count_365d number(10) NOT NULL,
  cv_measurement_below number(10) NOT NULL,
  cv_measurement_above number(10) NOT NULL,
  cv_concept_counts number(10) NOT NULL,
  cv_risk_scores number(10) NOT NULL,
  cv_risk_scores_charlson number(10) NOT NULL,
  cv_risk_scores_dcsi number(10) NOT NULL,
  cv_risk_scores_chads2 number(10) NOT NULL,
  cv_risk_scores_chads2vasc number(10) NOT NULL,
  cv_interaction_year number(10) NOT NULL,
  cv_interaction_month number(10) NOT NULL,
  del_covariates_small_count number(10) NOT NULL,
  created Timestamp(3) NOT NULL,
  modified Timestamp(3) NULL,
  created_by varchar2(255) NULL,
  modified_by varchar2(255) NULL
);
