CREATE SEQUENCE HERACLES_VIZ_DATA_SEQUENCE START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NOCYCLE;

CREATE TABLE HERACLES_VISUALIZATION_DATA (
	id Number(10) NOT NULL ,
	cohort_definition_id Number(10) NOT NULL ,
	source_id Number(10) NOT NULL,
	visualization_key VARCHAR(300) NOT NULL,
	drilldown_id number(10),
	data CLOB NOT NULL,
	end_time Timestamp(3) NOT NULL,
	CONSTRAINT PK_heracles_viz_data PRIMARY KEY (id) 
);

CREATE UNIQUE INDEX HERACLES_VIZ_DATA_UNQ_IDX ON HERACLES_VISUALIZATION_DATA (COHORT_DEFINITION_ID, SOURCE_ID, VISUALIZATION_KEY, DRILLDOWN_ID);
CREATE INDEX HERACLES_VIZ_DATA_IDX ON HERACLES_VISUALIZATION_DATA (COHORT_DEFINITION_ID, SOURCE_ID, VISUALIZATION_KEY);
