-- Author: Gleb Malikov
-- 2015
-- Oracle script

CREATE SEQUENCE SEC_USER_SEQUENCE MAXVALUE 9223372036854775807 NOCYCLE;
CREATE TABLE SEC_USER(
    ID                  INTEGER NOT NULL,
    LOGIN               VARCHAR2(50),
    PASSWORD            VARCHAR2(255),
    SALT                VARCHAR2(255),
    NAME                VARCHAR2(100)
);

COMMENT ON COLUMN SEC_USER.ID IS 'primary key';
COMMENT ON COLUMN SEC_USER.LOGIN IS 'Login';
COMMENT ON COLUMN SEC_USER.PASSWORD IS 'Password';
COMMENT ON COLUMN SEC_USER.SALT IS 'Salt for password encoding';
COMMENT ON COLUMN SEC_USER.NAME IS 'Displayed name for user';

CREATE SEQUENCE SEC_ROLE_SEQUENCE MAXVALUE 9223372036854775807 NOCYCLE;
CREATE TABLE SEC_ROLE (
    ID                  INTEGER NOT NULL,
    NAME                VARCHAR2(255)
);

COMMENT ON COLUMN SEC_ROLE.ID IS 'primary key';
COMMENT ON COLUMN SEC_ROLE.NAME IS 'Role name';

CREATE TABLE SEC_USER_ROLE(
    USER_ID             INTEGER NOT NULL,
    ROLE_ID             INTEGER
);

COMMENT ON COLUMN SEC_USER_ROLE.USER_ID IS 'Foreign key to SEC_USER';
COMMENT ON COLUMN SEC_USER_ROLE.ROLE_ID IS 'Foreign key to SEC_ROLE';

CREATE SEQUENCE SEC_PERMISSION_SEQUENCE MAXVALUE 9223372036854775807 NOCYCLE;
CREATE TABLE SEC_PERMISSION(
    ID                  INTEGER NOT NULL,
    VALUE               VARCHAR2(255) NOT NULL,
    ROLE_ID             INTEGER NOT NULL
);

COMMENT ON COLUMN SEC_PERMISSION.ID IS 'Primary key';
COMMENT ON COLUMN SEC_PERMISSION.VALUE IS 'Permission';
COMMENT ON COLUMN SEC_PERMISSION.ROLE_ID IS 'Foreign key to SEC_ROLE';

-- add SEC_USER table constraints
ALTER TABLE SEC_USER ADD CONSTRAINT PK_SEC_USER PRIMARY KEY (ID);

-- add SEC_ROLE table constraints
ALTER TABLE SEC_ROLE ADD CONSTRAINT PK_SEC_ROLE PRIMARY KEY (ID);

-- add SEC_PERMISSION table constraints
ALTER TABLE SEC_PERMISSION ADD CONSTRAINT PK_SEC_PERMISSION PRIMARY KEY (ID);
ALTER TABLE SEC_PERMISSION ADD CONSTRAINT FK_PERM_TO_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SEC_ROLE(ID);

-- add SEC_USER_ROLE table constraints
ALTER TABLE SEC_USER_ROLE ADD CONSTRAINT FK_USER_ROLE_TO_USER FOREIGN KEY (USER_ID) REFERENCES SEC_USER(ID);
ALTER TABLE SEC_USER_ROLE ADD CONSTRAINT FK_USER_ROLE_TO_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SEC_ROLE(ID);






