DECLARE
    V_COL_EXISTS NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO V_COL_EXISTS
        FROM ALL_TAB_COLS
            WHERE COLUMN_NAME = 'MODE_ID'
            AND TABLE_NAME = 'COHORT_INCLUSION'
            AND OWNER = UPPER('${ohdsiSchema}');

    IF (V_COL_EXISTS = 0) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ${ohdsiSchema}.COHORT_INCLUSION ADD MODE_ID INT DEFAULT 0 NOT NULL';
    ELSE
        DBMS_OUTPUT.PUT_LINE('The column COHORT_INCLUSION.MODE_ID already exists');
    END IF;

    SELECT COUNT(*) INTO V_COL_EXISTS
        FROM ALL_TAB_COLS
            WHERE COLUMN_NAME = 'MODE_ID'
            AND TABLE_NAME = 'COHORT_INCLUSION_RESULT'
            AND OWNER = UPPER('${ohdsiSchema}');

    IF (V_COL_EXISTS = 0) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ${ohdsiSchema}.COHORT_INCLUSION_RESULT ADD MODE_ID INT DEFAULT 0 NOT NULL';
    ELSE
        DBMS_OUTPUT.PUT_LINE('The column COHORT_INCLUSION_RESULT.MODE_ID already exists');
    END IF;

    SELECT COUNT(*) INTO V_COL_EXISTS
        FROM ALL_TAB_COLS
            WHERE COLUMN_NAME = 'MODE_ID'
            AND TABLE_NAME = 'COHORT_SUMMARY_STATS'
            AND OWNER = UPPER('${ohdsiSchema}');

    IF (V_COL_EXISTS = 0) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ${ohdsiSchema}.COHORT_SUMMARY_STATS ADD MODE_ID INT DEFAULT 0 NOT NULL';
    ELSE
        DBMS_OUTPUT.PUT_LINE('The column COHORT_SUMMARY_STATS.MODE_ID already exists');
    END IF;
END;
