DELETE FROM ${ohdsiSchema}.CONCEPT_SET_GENERATION_INFO;

DROP SEQUENCE ${ohdsiSchema}.negative_controls_sequence;

CREATE SEQUENCE ${ohdsiSchema}.negative_controls_sequence START WITH 1 MAXVALUE 9223372036854775807 NOCYCLE;

DROP TABLE ${ohdsiSchema}.CONCEPT_SET_NEGATIVE_CONTROLS;

CREATE TABLE ${ohdsiSchema}.CONCEPT_SET_NEGATIVE_CONTROLS (
    id INTEGER NOT NULL,
    evidence_job_id NUMBER(19) NOT NULL,
    source_id INTEGER NOT NULL,
    concept_set_id INTEGER NOT NULL,
    CONSTRAINT PK_CONCEPT_SET_NC PRIMARY KEY (id)
);