DECLARE 
  num INTEGER;
BEGIN 
  SELECT count(*) INTO num FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PK_COHORT_INCL';
  IF num > 1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ${ohdsiSchema}.cohort_inclusion DROP PRIMARY KEY';
  END IF;
END;