DROP TABLE SEC_ROLE_PERMISSION;
DROP TABLE SEC_USER_ROLE;
DROP TABLE SEC_PERMISSION;
DROP TABLE SEC_ROLE;
DROP TABLE SEC_USER;

DROP SEQUENCE SEC_ROLE_PERMISSION_SEQUENCE;
DROP SEQUENCE SEC_USER_ROLE_SEQUENCE;
DROP SEQUENCE SEC_PERMISSION_SEQUENCE;
DROP SEQUENCE SEC_ROLE_SEQUENCE;
DROP SEQUENCE SEC_USER_SEQUENCE;