# Broadsea PostgreSQL Configuration
datasource.driverClassName=org.postgresql.Driver
datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=webapi
datasource.username=postgres
datasource.password=mypass
datasource.dialect=postgresql
datasource.ohdsi.schema=webapi
datasource.dialect.source=postgresql

# Flyway Configuration
flyway.datasource.driverClassName=org.postgresql.Driver
flyway.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=webapi
flyway.datasource.username=postgres
flyway.datasource.password=mypass
flyway.schemas=webapi
flyway.placeholders.ohdsiSchema=webapi
flyway.locations=classpath:db/migration/postgresql
flyway.validateOnMigrate=false

# Hibernate Configuration
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JPA Configuration  
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default_schema=webapi
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true

# Spring Batch Configuration
spring.batch.repository.tableprefix=webapi.BATCH_
spring.batch.repository.isolationLevelForCreate=ISOLATION_DEFAULT
spring.batch.taskExecutor.corePoolSize=5
spring.batch.taskExecutor.maxPoolSize=10
spring.batch.taskExecutor.queueCapacity=500
spring.batch.taskExecutor.threadGroupName=batchGroup
spring.batch.taskExecutor.threadNamePrefix=batchExec

# Server Configuration
server.port=8080

# Security Configuration
security.provider=DisabledSecurity
security.cors.enabled=true
security.origin=*
security.token.expiration=43200
security.defaultGlobalReadPermissions=true
security.ssl.enabled=false

# Hikari Configuration
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.connection-test-query-timeout=1000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=30000

# CDM Properties
source.name=SYNPUF5PCT
cdm.version=5

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.level.root=INFO
logging.level.org.ohdsi=INFO
logging.level.org.springframework.jdbc=DEBUG

# Spring Cache
spring.cache.type=none

# Person Settings
person.viewDates=false

# Heracles Settings
heracles.smallcellcount=5

# Jasypt Configuration
jasypt.encryptor.enabled=false

# Organization Settings
organization.name=OHDSI

# Audit Trail Settings
audit.trail.enabled=false

# Cache Settings
cdm.result.cache.warming.enable=false
cdm.cache.achilles.warming.enable=false
cdm.cache.cron.warming.enable=false

# GIS Settings
atlasgis.enabled=false

# I18n Settings
i18n.enabled=false
i18n.defaultLocale=en

# Tag Settings
tag.enabled=false

# Versioning Settings
versioning.maxAttempt=3
