--Needed for JPA/hibernate
CREATE TABLE ${ohdsiSchema}.HIBERNATE_SEQUENCE (ID BIGINT IDENTITY);

--Example
CREATE TABLE ${ohdsiSchema}.EXAMPLEAPP_WIDGET  (
	ID BIGINT  NOT NULL PRIMARY KEY ,
	NAME VARCHAR(50)
);
