CREATE SEQUENCE SEC_USER_SEQUENCE START WITH 1000 INCREMENT BY 1 MAXVALUE 9223372036854775807 NO CYCLE;
CREATE TABLE SEC_USER(
    ID                  INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEC_USER_SEQUENCE,
    LOGIN               VARCHAR(50),
    PASSWORD            VARCHAR(255),
    SALT                VARCHAR(255),
    NAME                VARCHAR(100)
);

CREATE SEQUENCE SEC_ROLE_SEQUENCE START WITH 1000 INCREMENT BY 1 MAXVALUE 9223372036854775807 NO CYCLE;
CREATE TABLE SEC_ROLE (
    ID                  INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEC_ROLE_SEQUENCE,
    NAME                VARCHAR(255)
);

CREATE SEQUENCE SEC_USER_ROLE_SEQUENCE START WITH 1000 INCREMENT BY 1 MAXVALUE 9223372036854775807 NO CYCLE;
CREATE TABLE SEC_USER_ROLE(
    ID                  INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEC_USER_ROLE_SEQUENCE,
    USER_ID             INTEGER NOT NULL,
    ROLE_ID             INTEGER NOT NULL,
    STATUS		VARCHAR(255) NULL	
);

CREATE SEQUENCE SEC_PERMISSION_SEQUENCE START WITH 1000 INCREMENT BY 1 MAXVALUE 9223372036854775807 NO CYCLE;
CREATE TABLE SEC_PERMISSION(
    ID                  INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEC_PERMISSION_SEQUENCE,
    VALUE               VARCHAR(255) NOT NULL,
    DESCRIPTION		VARCHAR(255) NULL
);

CREATE SEQUENCE SEC_ROLE_PERMISSION_SEQUENCE START WITH 1000 INCREMENT BY 1 MAXVALUE 9223372036854775807 NO CYCLE;
CREATE TABLE SEC_ROLE_PERMISSION (
    ID			INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEC_ROLE_PERMISSION_SEQUENCE,
    ROLE_ID             INTEGER NOT NULL,
    PERMISSION_ID	INTEGER NOT NULL,
    STATUS		VARCHAR(255) NULL
);


-- add SEC_USER table constraints
ALTER TABLE SEC_USER ADD CONSTRAINT PK_SEC_USER PRIMARY KEY (ID);

-- add SEC_ROLE table constraints
ALTER TABLE SEC_ROLE ADD CONSTRAINT PK_SEC_ROLE PRIMARY KEY (ID);

-- add SEC_PERMISSION table constraints
ALTER TABLE SEC_PERMISSION ADD CONSTRAINT PK_SEC_PERMISSION PRIMARY KEY (ID);

-- add SEC_USER_ROLE table constraints
ALTER TABLE SEC_USER_ROLE ADD CONSTRAINT PK_SEC_USER_ROLE PRIMARY KEY (ID);
ALTER TABLE SEC_USER_ROLE ADD CONSTRAINT FK_USER_ROLE_TO_USER FOREIGN KEY (USER_ID) REFERENCES SEC_USER(ID);
ALTER TABLE SEC_USER_ROLE ADD CONSTRAINT FK_USER_ROLE_TO_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SEC_ROLE(ID);

-- add SEC_ROLE_PERMISSION table constraints
ALTER TABLE SEC_ROLE_PERMISSION ADD CONSTRAINT PK_SEC_ROLE_PERMISSION PRIMARY KEY (ID);
ALTER TABLE SEC_ROLE_PERMISSION ADD CONSTRAINT FK_ROLE_PERMISSION_TO_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SEC_ROLE(ID);
ALTER TABLE SEC_ROLE_PERMISSION ADD CONSTRAINT FK_ROLE_PERMISSION_TO_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES SEC_PERMISSION(ID);
