CREATE TABLE [${ohdsiSchema}].[plp]
(
  plp_id [int] IDENTITY(1,1) NOT NULL,
  name [varchar](255) NOT NULL,
  treatment_id [int] NOT NULL,
  outcome_id [int] NOT NULL,
  model_type [varchar](255) NOT NULL,
  time_at_risk_start [int] NOT NULL,
  time_at_risk_end [int] NOT NULL,
  add_exposure_days_to_end [int] NOT NULL,
  minimum_washout_period [int] NOT NULL,
  minimum_days_at_risk [int] NOT NULL,
  require_time_at_risk [int] NOT NULL,
  minimum_time_at_risk [int] NOT NULL,
  [sample] [int] NOT NULL,
  sample_size [int] NOT NULL,
  first_exposure_only [int] NOT NULL,
  include_all_outcomes [int] NOT NULL,
  rm_prior_outcomes [int] NOT NULL,
  prior_outcome_lookback [int] NOT NULL,
  test_split [int] NOT NULL,
  test_fraction [varchar](255) NULL,
  n_fold [varchar](255) NULL,
  mo_alpha [varchar](255) NULL,
  mo_class_weight [varchar](255) NULL,
  mo_index_folder [varchar](255) NULL,
  mo_k [varchar](255) NULL,
  mo_learn_rate [varchar](255) NULL,
  mo_learning_rate [varchar](255) NULL,
  mo_max_depth [varchar](255) NULL,
  mo_min_impurity_split [varchar](255) NULL,
  mo_min_rows [varchar](255) NULL,
  mo_min_samples_leaf [varchar](255) NULL,
  mo_min_samples_split [varchar](255) NULL,
  mo_mtries [varchar](255) NULL,
  mo_nestimators [varchar](255) NULL,
  mo_nthread [varchar](255) NULL,
  mo_ntrees [varchar](255) NULL,
  mo_plot [varchar](255) NULL,
  mo_seed [varchar](255) NULL,
  mo_size [varchar](255) NULL,
  mo_variance [varchar](255) NULL,
  mo_var_imp [varchar](255) NULL,
  cv_exclusion_id [int] NOT NULL,
  cv_inclusion_id [int] NOT NULL,
  cv_demographics [int] NOT NULL,
  cv_demographics_gender [int] NOT NULL,
  cv_demographics_race [int] NOT NULL,
  cv_demographics_ethnicity [int] NOT NULL,
  cv_demographics_age [int] NOT NULL,
  cv_demographics_year [int] NOT NULL,
  cv_demographics_month [int] NOT NULL,
  cv_condition_occ [int] NOT NULL,
  cv_condition_occ_365d [int] NOT NULL,
  cv_condition_occ_30d [int] NOT NULL,
  cv_condition_occ_inpt180d [int] NOT NULL,
  cv_condition_era [int] NOT NULL,
  cv_condition_era_ever [int] NOT NULL,
  cv_condition_era_overlap [int] NOT NULL,
  cv_condition_group [int] NOT NULL,
  cv_condition_group_meddra [int] NOT NULL,
  cv_condition_group_snomed [int] NOT NULL,
  cv_drug_exposure [int] NOT NULL,
  cv_drug_exposure_365d [int] NOT NULL,
  cv_drug_exposure_30d [int] NOT NULL,
  cv_drug_era [int] NOT NULL,
  cv_drug_era_365d [int] NOT NULL,
  cv_drug_era_30d [int] NOT NULL,
  cv_drug_era_overlap [int] NOT NULL,
  cv_drug_era_ever [int] NOT NULL,
  cv_drug_group [int] NOT NULL,
  cv_procedure_occ [int] NOT NULL,
  cv_procedure_occ_365d [int] NOT NULL,
  cv_procedure_occ_30d [int] NOT NULL,
  cv_procedure_group [int] NOT NULL,
  cv_observation [int] NOT NULL,
  cv_observation_365d [int] NOT NULL,
  cv_observation_30d [int] NOT NULL,
  cv_observation_count_365d [int] NOT NULL,
  cv_measurement [int] NOT NULL,
  cv_measurement_365d [int] NOT NULL,
  cv_measurement_30d [int] NOT NULL,
  cv_measurement_count_365d [int] NOT NULL,
  cv_measurement_below [int] NOT NULL,
  cv_measurement_above [int] NOT NULL,
  cv_concept_counts [int] NOT NULL,
  cv_risk_scores [int] NOT NULL,
  cv_risk_scores_charlson [int] NOT NULL,
  cv_risk_scores_dcsi [int] NOT NULL,
  cv_risk_scores_chads2 [int] NOT NULL,
  cv_risk_scores_chads2vasc [int] NOT NULL,
  cv_interaction_year [int] NOT NULL,
  cv_interaction_month [int] NOT NULL,
  del_covariates_small_count [int] NOT NULL,
  created [datetime] NOT NULL,
  modified [datetime] NULL,
  created_by [varchar](255) NULL,
  modified_by [varchar](255) NULL
)
