CREATE TABLE ${ohdsiSchema}.[TEMP_EXAMPLEAPP_WIDGET]
(
        [ID] [bigint] NOT NULL identity(1,1),
        [NAME] [varchar](50) NULL
);

SET IDENTITY_INSERT ${ohdsiSchema}.[TEMP_EXAMPLEAPP_WIDGET] ON;

INSERT INTO ${ohdsiSchema}.[TEMP_EXAMPLEAPP_WIDGET] (ID, NAME)
SELECT ID, NAME from ${ohdsiSchema}.[EXAMPLEAPP_WIDGET] TABLOCKX;

SET IDENTITY_INSERT ${ohdsiSchema}.[TEMP_EXAMPLEAPP_WIDGET] OFF;

DROP TABLE ${ohdsiSchema}.[EXAMPLEAPP_WIDGET];

Exec sp_rename '${ohdsiSchema}.TEMP_EXAMPLEAPP_WIDGET', 'EXAMPLEAPP_WIDGET';

ALTER TABLE ${ohdsiSchema}.EXAMPLEAPP_WIDGET 
  ADD CONSTRAINT PK_EXAMPLEAPP_WIDGET PRIMARY KEY CLUSTERED ([ID]) 
ON [PRIMARY];

DROP TABLE ${ohdsiSchema}.HIBERNATE_SEQUENCE;
