
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1300,'Number of persons with at least one measurement occurrence, by measurement_concept_id','measurement_concept_id',null,null,null,null,'MEASUREMENT');
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1301,'Number of measurement occurrence records, by measurement_concept_id','measurement_concept_id',null,null,null,null,'MEASUREMENT');
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1302,'Number of persons by measurement occurrence start month, by measurement_concept_id','measurement_concept_id','calendar month',null,null,null,'MEASUREMENT');
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1303,'Number of distinct measurement occurrence concepts per person',null,null,null,null,null,'MEASUREMENT');
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1304,'Number of persons with at least one measurement occurrence, by measurement_concept_id by calendar year by gender by age decile','measurement_concept_id','calendar year','gender_concept_id','age decile',null,'MEASUREMENT');
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1305,'Number of measurement occurrence records, by measurement_concept_id by measurement_type_concept_id','measurement_concept_id','measurement_type_concept_id',null,null,null,'MEASUREMENT');
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1306,'Distribution of age by measurement_concept_id','measurement_concept_id','gender_concept_id',null,null,null,'MEASUREMENT');
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1307,'Number of measurement occurrence records, by measurement_concept_id and unit_concept_id','measurement_concept_id','unit_concept_id',null,null,null,'MEASUREMENT');
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1309,'Number of measurement records with invalid person_id',null,null,null,null,null,'MEASUREMENT');
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1310,'Number of measurement records outside valid measurement period',null,null,null,null,null,'MEASUREMENT');
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1312,'Number of measurement records with invalid provider_id',null,null,null,null,null,'MEASUREMENT');
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1313,'Number of measurement records with invalid visit_id',null,null,null,null,null,'MEASUREMENT');
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1314,'Number of measurement records with no value (numeric, string, or concept)',null,null,null,null,null,'MEASUREMENT');
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1315,'Distribution of numeric values, by measurement_concept_id and unit_concept_id',null,null,null,null,null,'MEASUREMENT');
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1316,'Distribution of low range, by measurement_concept_id and unit_concept_id',null,null,null,null,null,'MEASUREMENT');
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1317,'Distribution of high range, by measurement_concept_id and unit_concept_id',null,null,null,null,null,'MEASUREMENT');
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1318,'Number of measurement records below/within/above normal range, by measurement_concept_id and unit_concept_id',null,null,null,null,null,'MEASUREMENT');
insert into ${ohdsiSchema}.heracles_analysis (ANALYSIS_ID,ANALYSIS_NAME,STRATUM_1_NAME,STRATUM_2_NAME,STRATUM_3_NAME,STRATUM_4_NAME,STRATUM_5_NAME,ANALYSIS_TYPE) values (1320,'Number of measurement records  by measurement start month','calendar month',null,null,null,null,'MEASUREMENT');