if ((select columnproperty(object_id('[dbo].[EXAMPLEAPP_WIDGET]'),'ID','IsIdentity')) = 0) 
begin
  CREATE TABLE dbo.[TEMP_EXAMPLEAPP_WIDGET]
  (
          [ID] [bigint] NOT NULL identity(1,1),
          [NAME] [varchar](50) NULL
  );

  SET IDENTITY_INSERT dbo.[TEMP_EXAMPLEAPP_WIDGET] ON;

  IF EXISTS(SELECT * FROM dbo.[EXAMPLEAPP_WIDGET])
   EXEC('INSERT INTO dbo.[TEMP_EXAMPLEAPP_WIDGET] (ID, NAME)
      SELECT ID, NAME from dbo.[EXAMPLEAPP_WIDGET] TABLOCKX');

  SET IDENTITY_INSERT dbo.[TEMP_EXAMPLEAPP_WIDGET] OFF;

  DROP TABLE dbo.[EXAMPLEAPP_WIDGET];

  Exec sp_rename 'TEMP_EXAMPLEAPP_WIDGET', 'EXAMPLEAPP_WIDGET';

  ALTER TABLE dbo.EXAMPLEAPP_WIDGET ADD CONSTRAINT
      PK_EXAMPLEAPP_WIDGET PRIMARY KEY CLUSTERED 
      (
                  [ID]
      ) ON [PRIMARY];
end
;

IF (EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = 'dbo' 
                 AND  TABLE_NAME = 'HIBERNATE_SEQUENCE'))
BEGIN
  DROP TABLE dbo.HIBERNATE_SEQUENCE;
END
;
