CREATE TABLE ${ohdsiSchema}.HERACLES_VISUALIZATION_DATA (
	id integer NOT NULL ,
	cohort_definition_id integer NOT NULL ,
	source_id integer NOT NULL,
	visualization_key VARCHAR(300) NOT NULL,
	drilldown_id integer,
	data TEXT NOT NULL,
	end_time Timestamp NOT NULL,
	CONSTRAINT PK_heracles_viz_data PRIMARY KEY (id) 
);

CREATE UNIQUE INDEX HERACLES_VIZ_DATA_UNQ_IDX ON ${ohdsiSchema}.HERACLES_VISUALIZATION_DATA (COHORT_DEFINITION_ID, SOURCE_ID, VISUALIZATION_KEY, DRILLDOWN_ID);
CREATE INDEX HERACLES_VIZ_DATA_IDX ON ${ohdsiSchema}.HERACLES_VISUALIZATION_DATA (COHORT_DEFINITION_ID, SOURCE_ID, VISUALIZATION_KEY);
