IF (EXISTS (SELECT * 
            FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_SCHEMA = '${ohdsiSchema}' 
            AND  TABLE_NAME = 'CONCEPT_SET_NEGATIVE_CONTROLS'))
BEGIN
    DROP TABLE [${ohdsiSchema}].[CONCEPT_SET_NEGATIVE_CONTROLS]
END

CREATE TABLE [${ohdsiSchema}].CONCEPT_SET_NEGATIVE_CONTROLS (
    [id] [int] IDENTITY(1,1) NOT NULL,
    source_id int NOT NULL,
    concept_set_id int NOT NULL,
    concept_set_name varchar(255) NOT NULL,
    concept_id int NOT NULL,
    concept_name varchar(255) NOT NULL,
    domain_id varchar(255) NOT NULL,
    MEDLINE_CT float NULL,
    MEDLINE_CASE float NULL,
    MEDLINE_OTHER float NULL,
    SEMMEDDB_CT_T float NULL,
    SEMMEDDB_CASE_T float NULL,
    SEMMEDDB_OTHER_T float NULL,
    SEMMEDDB_CT_F float NULL,
    SEMMEDDB_CASE_F float NULL,
    SEMMEDDB_OTHER_F float NULL,
    EU_SPC float NULL,
    SPL_ADR float NULL,
    AERS float NULL,
    AERS_PRR float NULL,
    MEDLINE_CT_SCALED float NULL,
    MEDLINE_CASE_SCALED float NULL,
    MEDLINE_OTHER_SCALED float NULL,
    SEMMEDDB_CT_T_SCALED float NULL,
    SEMMEDDB_CASE_T_SCALED float NULL,
    SEMMEDDB_OTHER_T_SCALED float NULL,
    SEMMEDDB_CT_F_SCALED float NULL,
    SEMMEDDB_CASE_F_SCALED float NULL,
    SEMMEDDB_OTHER_F_SCALED float NULL,
    EU_SPC_SCALED float NULL,
    SPL_ADR_SCALED float NULL,
    AERS_SCALED float NULL,
    AERS_PRR_SCALED float NULL,
    MEDLINE_CT_BETA float NULL,
    MEDLINE_CASE_BETA float NULL,
    MEDLINE_OTHER_BETA float NULL,
    SEMMEDDB_CT_T_BETA float NULL,
    SEMMEDDB_CASE_T_BETA float NULL,
    SEMMEDDB_OTHER_T_BETA float NULL,
    SEMMEDDB_CT_F_BETA float NULL,
    SEMMEDDB_CASE_F_BETA float NULL,
    SEMMEDDB_OTHER_F_BETA float NULL,
    EU_SPC_BETA float NULL,
    SPL_ADR_BETA float NULL,
    AERS_BETA float NULL,
    AERS_PRR_BETA float NULL,
    RAW_PREDICTION float NULL,
    PREDICTION float NULL
 CONSTRAINT [PK_CONCEPT_SET_NEGATIVE_CONTROLS] PRIMARY KEY CLUSTERED 
  (
    [id] ASC
  ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
);

