-- Authors: Richard D Boyce, Erica Voss, Lee Evans
-- 2014/2015
-- SQL Server script

IF OBJECT_ID(N'${ohdsiSchema}.DRUG_HOI_EVIDENCE', N'U') IS NOT NULL DROP TABLE ${ohdsiSchema}.DRUG_HOI_EVIDENCE; 
IF OBJECT_ID('${ohdsiSchema}.DRUG_HOI_EVIDENCE_SEQUENCE', 'SO') IS NOT NULL DROP SEQUENCE ${ohdsiSchema}.DRUG_HOI_EVIDENCE_SEQUENCE;
CREATE SEQUENCE ${ohdsiSchema}.DRUG_HOI_EVIDENCE_SEQUENCE MAXVALUE 9223372036854775807 NO CYCLE;
CREATE TABLE ${ohdsiSchema}.DRUG_HOI_EVIDENCE (
    ID                          INTEGER NOT NULL DEFAULT NEXT VALUE FOR ${ohdsiSchema}.DRUG_HOI_EVIDENCE_SEQUENCE,
    DRUG_HOI_RELATIONSHIP       VARCHAR(50),
    EVIDENCE_TYPE               VARCHAR(4000),
    MODALITY                    VARCHAR(1),
    EVIDENCE_SOURCE_CODE_ID     INTEGER,
    STATISTIC_VALUE             NUMERIC NOT NULL,
    EVIDENCE_LINKOUT            VARCHAR(4000),
    STATISTIC_TYPE              VARCHAR(4000)
);

IF OBJECT_ID(N'${ohdsiSchema}.EVIDENCE_SOURCES', N'U') IS NOT NULL DROP TABLE ${ohdsiSchema}.EVIDENCE_SOURCES;
IF OBJECT_ID('${ohdsiSchema}.EVIDENCE_SOURCES_SEQUENCE', 'SO') IS NOT NULL DROP SEQUENCE ${ohdsiSchema}.EVIDENCE_SOURCES_SEQUENCE;
CREATE SEQUENCE ${ohdsiSchema}.EVIDENCE_SOURCES_SEQUENCE MAXVALUE 9223372036854775807 NO CYCLE;
CREATE TABLE ${ohdsiSchema}.EVIDENCE_SOURCES (
    ID                          INTEGER NOT NULL DEFAULT NEXT VALUE FOR ${ohdsiSchema}.EVIDENCE_SOURCES_SEQUENCE,
    TITLE                       VARCHAR(4000),
    DESCRIPTION                 VARCHAR(4000),
    CONTRIBUTER                 VARCHAR(4000),
    CREATOR                     VARCHAR(4000),
    CREATION_DATE               DATE NOT NULL, 
    RIGHTS                      VARCHAR(4000),
    SOURCE                      VARCHAR(4000)
);

IF OBJECT_ID(N'${ohdsiSchema}.DRUG_HOI_RELATIONSHIP', N'U') IS NOT NULL DROP TABLE ${ohdsiSchema}.DRUG_HOI_RELATIONSHIP;
CREATE TABLE ${ohdsiSchema}.DRUG_HOI_RELATIONSHIP (
    ID                          VARCHAR(50) NOT NULL,
    DRUG                        INTEGER,
    RXNORM_DRUG                 VARCHAR(4000),
    HOI                         INTEGER,
    SNOMED_HOI                  VARCHAR(4000)
);

IF OBJECT_ID(N'${ohdsiSchema}.LAERTES_SUMMARY', N'U') IS NOT NULL DROP TABLE ${ohdsiSchema}.LAERTES_SUMMARY;
IF OBJECT_ID('${ohdsiSchema}.LAERTES_SUMMARY_SEQUENCE', 'SO') IS NOT NULL DROP SEQUENCE ${ohdsiSchema}.LAERTES_SUMMARY_SEQUENCE;
CREATE SEQUENCE ${ohdsiSchema}.LAERTES_SUMMARY_SEQUENCE MAXVALUE 9223372036854775807 NO CYCLE;
CREATE TABLE ${ohdsiSchema}.LAERTES_SUMMARY (
	ID                      INTEGER NOT NULL DEFAULT NEXT VALUE FOR ${ohdsiSchema}.LAERTES_SUMMARY_SEQUENCE,
	REPORT_ORDER            INTEGER,
	REPORT_NAME             VARCHAR(4000),
	INGREDIENT_ID           INTEGER,
	INGREDIENT              VARCHAR(4000),
	CLINICAL_DRUG_ID        INTEGER,
	CLINICAL_DRUG           VARCHAR(4000),
	HOI_ID                  INTEGER,
	HOI                     VARCHAR(4000),
	CT_COUNT                INTEGER,
	CASE_COUNT              INTEGER,
	OTHER_COUNT             INTEGER,
	SPLICER_COUNT           INTEGER,
	EU_SPC_COUNT            INTEGER,
	SEMMEDDB_CT_COUNT       INTEGER,
	SEMMEDDB_CASE_COUNT	INTEGER,
	SEMMEDDB_NEG_CT_COUNT	INTEGER,
	SEMMEDDB_NEG_CASE_COUNT	INTEGER,
	EB05			NUMERIC,
	EBGM			NUMERIC,
	AERS_REPORT_COUNT	INTEGER
);

-- add EVIDENCE_SOURCES table constraints
ALTER TABLE ${ohdsiSchema}.EVIDENCE_SOURCES ADD CONSTRAINT PK_EVIDENCE_SOURCES PRIMARY KEY (ID);

-- add DRUG_HOI_RELATIONSHIP table constraints
ALTER TABLE ${ohdsiSchema}.DRUG_HOI_RELATIONSHIP ADD CONSTRAINT PK_DRUG_HOI_RELATIONSHIP PRIMARY KEY (ID);

-- add LAERTES_SUMMARY table constraints
ALTER TABLE ${ohdsiSchema}.LAERTES_SUMMARY ADD CONSTRAINT PK_LAERTES_SUMMARY PRIMARY KEY (ID);

-- add DRUG_HOI_EVIDENCE table constraints
ALTER TABLE ${ohdsiSchema}.DRUG_HOI_EVIDENCE ADD CONSTRAINT FK_DRUG_HOI_RELATIONSHIP FOREIGN KEY (DRUG_HOI_RELATIONSHIP) REFERENCES ${ohdsiSchema}.DRUG_HOI_RELATIONSHIP(ID);
ALTER TABLE ${ohdsiSchema}.DRUG_HOI_EVIDENCE ADD CONSTRAINT FK_EVIDENCE_SOURCES FOREIGN KEY (EVIDENCE_SOURCE_CODE_ID) REFERENCES ${ohdsiSchema}.EVIDENCE_SOURCES(ID);
ALTER TABLE ${ohdsiSchema}.DRUG_HOI_EVIDENCE ADD CONSTRAINT PK_DRUG_HOI_EVIDENCE PRIMARY KEY (ID);
