CREATE INDEX BJEP_JOB_STRING_IDX ON ${ohdsiSchema}.BATCH_JOB_EXECUTION_PARAMS (JOB_EXECUTION_ID,STRING_VAL);

TRUNCATE TABLE ${ohdsiSchema}.BATCH_JOB_EXECUTION_SEQ;
DROP TABLE ${ohdsiSchema}.BATCH_JOB_EXECUTION_SEQ;

TRUNCATE TABLE ${ohdsiSchema}.BATCH_JOB_SEQ;
DROP TABLE ${ohdsiSchema}.BATCH_JOB_SEQ;

TRUNCATE TABLE ${ohdsiSchema}.BATCH_STEP_EXECUTION_SEQ;
DROP TABLE ${ohdsiSchema}.BATCH_STEP_EXECUTION_SEQ;