DROP TABLE ${ohdsiSchema}.BATCH_STEP_EXECUTION_SEQ;

CREATE SEQUENCE ${ohdsiSchema}.BATCH_STEP_EXECUTION_SEQ
  AS BIGINT
  START WITH 1
  NO CYCLE;
GO

ALTER TABLE ${ohdsiSchema}.BATCH_STEP_EXECUTION ADD bid BIGINT;
GO

UPDATE ${ohdsiSchema}.BATCH_STEP_EXECUTION SET bid = STEP_EXECUTION_ID;
GO

DECLARE @pk nvarchar(512);
SELECT @pk = Name FROM SYS.KEY_CONSTRAINTS WHERE [type] = 'PK' AND PARENT_OBJECT_ID = OBJECT_ID('${ohdsiSchema}.BATCH_STEP_EXECUTION')

IF @pk IS NOT NULL
  ALTER TABLE ${ohdsiSchema}.BATCH_STEP_EXECUTION_CONTEXT DROP CONSTRAINT STEP_EXEC_CTX_FK;
  EXEC('ALTER TABLE ${ohdsiSchema}.BATCH_STEP_EXECUTION DROP CONSTRAINT ' + @pk);
GO

DECLARE @df nvarchar(512);
SELECT @df = Name FROM SYS.DEFAULT_CONSTRAINTS WHERE PARENT_OBJECT_ID = OBJECT_ID('${ohdsiSchema}.BATCH_STEP_EXECUTION')

IF @df IS NOT NULL
  EXEC('ALTER TABLE ${ohdsiSchema}.BATCH_STEP_EXECUTION DROP CONSTRAINT ' + @df);
GO

ALTER TABLE ${ohdsiSchema}.BATCH_STEP_EXECUTION DROP COLUMN STEP_EXECUTION_ID;
GO

EXEC sp_rename '[${ohdsiSchema}].BATCH_STEP_EXECUTION.bid', 'STEP_EXECUTION_ID', 'COLUMN';
GO

ALTER TABLE ${ohdsiSchema}.BATCH_STEP_EXECUTION ALTER COLUMN STEP_EXECUTION_ID BIGINT NOT NULL;
GO

ALTER TABLE ${ohdsiSchema}.BATCH_STEP_EXECUTION ADD CONSTRAINT DF_bat_step_exec_id DEFAULT (NEXT VALUE FOR ${ohdsiSchema}.BATCH_STEP_EXECUTION_SEQ) FOR STEP_EXECUTION_ID;
GO

ALTER TABLE ${ohdsiSchema}.BATCH_STEP_EXECUTION ADD CONSTRAINT PK_bat_step_exec PRIMARY KEY clustered(STEP_EXECUTION_ID asc);
GO

ALTER TABLE ${ohdsiSchema}.BATCH_STEP_EXECUTION_CONTEXT ADD CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID) REFERENCES ${ohdsiSchema}.BATCH_STEP_EXECUTION(STEP_EXECUTION_ID);
GO

DECLARE @cur_id_val INT;
DECLARE @sql NVARCHAR(MAX);

SELECT @cur_id_val = coalesce(MAX(STEP_EXECUTION_ID), 1) FROM ${ohdsiSchema}.BATCH_STEP_EXECUTION;
SET @sql = N'ALTER SEQUENCE ${ohdsiSchema}.BATCH_STEP_EXECUTION_SEQ RESTART WITH ' + CAST(@cur_id_val as NVARCHAR(20)) + ';';

EXEC sp_executesql @sql;
GO

DROP TABLE ${ohdsiSchema}.BATCH_JOB_EXECUTION_SEQ;

CREATE SEQUENCE ${ohdsiSchema}.BATCH_JOB_EXECUTION_SEQ
  AS BIGINT
  START WITH 1
  NO CYCLE;
GO

ALTER TABLE ${ohdsiSchema}.BATCH_JOB_EXECUTION ADD bid BIGINT;
GO

UPDATE ${ohdsiSchema}.BATCH_JOB_EXECUTION SET bid = JOB_EXECUTION_ID;
GO

DECLARE @pk nvarchar(512);
SELECT @pk = Name FROM SYS.KEY_CONSTRAINTS WHERE [type] = 'PK' AND PARENT_OBJECT_ID = OBJECT_ID('${ohdsiSchema}.BATCH_JOB_EXECUTION')

IF @pk IS NOT NULL
  ALTER TABLE ${ohdsiSchema}.BATCH_JOB_EXECUTION_CONTEXT DROP CONSTRAINT JOB_EXEC_CTX_FK;
  ALTER TABLE ${ohdsiSchema}.BATCH_JOB_EXECUTION_PARAMS DROP CONSTRAINT JOB_EXEC_PARAMS_FK;
  ALTER TABLE ${ohdsiSchema}.BATCH_STEP_EXECUTION DROP CONSTRAINT JOB_EXEC_STEP_FK;
  EXEC('ALTER TABLE ${ohdsiSchema}.BATCH_JOB_EXECUTION DROP CONSTRAINT ' + @pk);
GO

DECLARE @df nvarchar(512);
SELECT @df = Name FROM SYS.DEFAULT_CONSTRAINTS WHERE PARENT_OBJECT_ID = OBJECT_ID('${ohdsiSchema}.BATCH_JOB_EXECUTION')

IF @df IS NOT NULL
  EXEC('ALTER TABLE ${ohdsiSchema}.BATCH_JOB_EXECUTION DROP CONSTRAINT ' + @df);
GO

ALTER TABLE ${ohdsiSchema}.BATCH_JOB_EXECUTION DROP COLUMN JOB_EXECUTION_ID;
GO

EXEC sp_rename '[${ohdsiSchema}].BATCH_JOB_EXECUTION.bid', 'JOB_EXECUTION_ID', 'COLUMN';
GO

ALTER TABLE ${ohdsiSchema}.BATCH_JOB_EXECUTION ALTER COLUMN JOB_EXECUTION_ID BIGINT NOT NULL;
GO

ALTER TABLE ${ohdsiSchema}.BATCH_JOB_EXECUTION ADD CONSTRAINT DF_bat_job_exec_id DEFAULT (NEXT VALUE FOR ${ohdsiSchema}.BATCH_JOB_EXECUTION_SEQ) FOR JOB_EXECUTION_ID;
GO

ALTER TABLE ${ohdsiSchema}.BATCH_JOB_EXECUTION ADD CONSTRAINT PK_bat_job_exec PRIMARY KEY clustered(JOB_EXECUTION_ID asc);
GO

ALTER TABLE ${ohdsiSchema}.BATCH_JOB_EXECUTION_CONTEXT ADD CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES ${ohdsiSchema}.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID);
GO

ALTER TABLE ${ohdsiSchema}.BATCH_JOB_EXECUTION_PARAMS ADD CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES ${ohdsiSchema}.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID);
GO

ALTER TABLE ${ohdsiSchema}.BATCH_STEP_EXECUTION ADD CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES ${ohdsiSchema}.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID);
GO

DECLARE @cur_id_val INT;
DECLARE @sql NVARCHAR(MAX);

SELECT @cur_id_val = coalesce(MAX(JOB_EXECUTION_ID), 1) FROM ${ohdsiSchema}.BATCH_JOB_EXECUTION;
SET @sql = N'ALTER SEQUENCE ${ohdsiSchema}.BATCH_JOB_EXECUTION_SEQ RESTART WITH ' + CAST(@cur_id_val as NVARCHAR(20)) + ';';

EXEC sp_executesql @sql;
GO

DROP TABLE ${ohdsiSchema}.BATCH_JOB_SEQ;

CREATE SEQUENCE ${ohdsiSchema}.BATCH_JOB_SEQ
  AS BIGINT
  START WITH 1
  NO CYCLE;
GO

ALTER TABLE ${ohdsiSchema}.BATCH_JOB_INSTANCE ADD bid BIGINT;
GO

UPDATE ${ohdsiSchema}.BATCH_JOB_INSTANCE SET bid = JOB_INSTANCE_ID;
GO

DECLARE @pk nvarchar(512);
SELECT @pk = Name FROM SYS.KEY_CONSTRAINTS WHERE [type] = 'PK' AND PARENT_OBJECT_ID = OBJECT_ID('${ohdsiSchema}.BATCH_JOB_INSTANCE')

IF @pk IS NOT NULL
  ALTER TABLE ${ohdsiSchema}.BATCH_JOB_EXECUTION DROP CONSTRAINT JOB_INST_EXEC_FK;
  EXEC('ALTER TABLE ${ohdsiSchema}.BATCH_JOB_INSTANCE DROP CONSTRAINT ' + @pk);
GO

DECLARE @df nvarchar(512);
SELECT @df = Name FROM SYS.DEFAULT_CONSTRAINTS WHERE PARENT_OBJECT_ID = OBJECT_ID('${ohdsiSchema}.BATCH_JOB_INSTANCE')

IF @df IS NOT NULL
  EXEC('ALTER TABLE ${ohdsiSchema}.BATCH_JOB_INSTANCE DROP CONSTRAINT ' + @df);
GO

ALTER TABLE ${ohdsiSchema}.BATCH_JOB_INSTANCE DROP COLUMN JOB_INSTANCE_ID;
GO

EXEC sp_rename '[${ohdsiSchema}].BATCH_JOB_INSTANCE.bid', 'JOB_INSTANCE_ID', 'COLUMN';
GO

ALTER TABLE ${ohdsiSchema}.BATCH_JOB_INSTANCE ALTER COLUMN JOB_INSTANCE_ID BIGINT NOT NULL;
GO

ALTER TABLE ${ohdsiSchema}.BATCH_JOB_INSTANCE ADD CONSTRAINT DF_bat_job_instance_id DEFAULT (NEXT VALUE FOR ${ohdsiSchema}.BATCH_JOB_SEQ) FOR JOB_INSTANCE_ID;
GO

ALTER TABLE ${ohdsiSchema}.BATCH_JOB_INSTANCE ADD CONSTRAINT PK_bat_job_instance PRIMARY KEY clustered(JOB_INSTANCE_ID asc);
GO

ALTER TABLE ${ohdsiSchema}.BATCH_JOB_EXECUTION ADD CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID) REFERENCES ${ohdsiSchema}.BATCH_JOB_INSTANCE(JOB_INSTANCE_ID);
GO

DECLARE @cur_id_val INT;
DECLARE @sql NVARCHAR(MAX);

SELECT @cur_id_val = coalesce(MAX(JOB_INSTANCE_ID), 1) FROM ${ohdsiSchema}.BATCH_JOB_INSTANCE;
SET @sql = N'ALTER SEQUENCE ${ohdsiSchema}.BATCH_JOB_SEQ RESTART WITH ' + CAST(@cur_id_val as NVARCHAR(20)) + ';';

EXEC sp_executesql @sql;
GO