select CONCEPT_ID, CONCEPT_NAME, ISNULL(STANDARD_CONCEPT,'N') STANDARD_CONCEPT, ISNULL(INVALID_REASON,'V') INVALID_REASON, CONCEPT_CODE, CONCEPT_CLASS_ID, DOMAIN_ID, VOCABULARY_ID
from omop_v5.CONCEPT 
where (LOWER(CONCEPT_NAME) LIKE ? or CONCEPT_CODE LIKE ? or CAST(CONCEPT_ID as VARCHAR(255)) = ?)

order by CONCEPT_NAME ASC
