select distinct * from (
  select ANCESTOR_CONCEPT_ID CONCEPT_ID, CONCEPT_NAME, ISNULL(STANDARD_CONCEPT,'N') STANDARD_CONCEPT, ISNULL(c.INVALID_REASON,'V') INVALID_REASON, CONCEPT_CODE, CONCEPT_CLASS_ID, DOMAIN_ID, c.VOCABULARY_ID, c.VALID_START_DATE, c.VALID_END_DATE, 'Has ancestor of' RELATIONSHIP_NAME, MIN_LEVELS_OF_SEPARATION RELATIONSHIP_DISTANCE
      from @CDM_schema.concept_ancestor ca
      join @CDM_schema.concept c on c.CONCEPT_ID = ca.ANCESTOR_CONCEPT_ID
      where DESCENDANT_CONCEPT_ID = @id
      and ANCESTOR_CONCEPT_ID <> @id
  union
  select DESCENDANT_CONCEPT_ID, CONCEPT_NAME, ISNULL(STANDARD_CONCEPT,'N') STANDARD_CONCEPT, ISNULL(c.INVALID_REASON,'V') INVALID_REASON, CONCEPT_CODE, CONCEPT_CLASS_ID, DOMAIN_ID, c.VOCABULARY_ID, c.VALID_START_DATE, c.VALID_END_DATE, 'Has descendant of' , MIN_LEVELS_OF_SEPARATION RELATIONSHIP_DISTANCE
      from @CDM_schema.concept_ancestor ca
      join @CDM_schema.concept c on c.CONCEPT_ID = ca.DESCENDANT_CONCEPT_ID
      where ANCESTOR_CONCEPT_ID = @id
      and DESCENDANT_CONCEPT_ID <> @id
) ALL_RELATED
order by RELATIONSHIP_DISTANCE ASC