select distinct c.CONCEPT_ID, CONCEPT_NAME, ISNULL(STANDARD_CONCEPT,'N') STANDARD_CONCEPT, ISNULL(c.INVALID_REASON,'V') INVALID_REASON, CONCEPT_CODE, CONCEPT_CLASS_ID, DOMAIN_ID, c.VOCABULARY_ID, RELATIONSHIP_ID
from @CDM_schema.concept_recommended cr
join @CDM_schema.concept c on cr.CONCEPT_ID_2 = c.CONCEPT_ID
where cr.CONCEPT_ID_1 in (@conceptList)
;