select distinct c.CONCEPT_ID, c.CONCEPT_NAME, ISNULL(c.STANDARD_CONCEPT,'N') STANDARD_CONCEPT, ISNULL(c.INVALID_REASON,'V') INVALID_REASON, c.CONCEPT_CODE, c.CONCEPT_CLASS_ID, c.DOMAIN_ID, c.VOCABULARY_ID, c.VALID_START_DATE, c.VALID_END_DATE, cr.RELATIONSHIP_ID
from @CDM_schema.concept_recommended cr
join @CDM_schema.concept c on cr.CONCEPT_ID_2 = c.CONCEPT_ID
where cr.CONCEPT_ID_1 in (@conceptList)
;