SELECT
   c.CONCEPT_ID,
   c.CONCEPT_NAME,
   COALESCE(c.STANDARD_CONCEPT, 'N') as STANDARD_CONCEPT,
   COALESCE(c.INVALID_REASON, 'V') as INVALID_REASON,
   c.CONCEPT_CODE,
   c.CONCEPT_CLASS_ID,
   c.DOMAIN_ID,
   c.VOCABULARY_ID,
   c.VALID_START_DATE,
   c.VALID_END_DATE,
   c.RELATIONSHIP_NAME,
   c.RELATIONSHIP_DISTANCE
FROM (
    SELECT
        c.CONCEPT_ID, CONCEPT_NAME, COALESCE(c.STANDARD_CONCEPT, 'N') as STANDARD_CONCEPT, COALESCE(c.INVALID_REASON, 'V') as INVALID_REASON,
        c.CONCEPT_CODE, c.CONCEPT_CLASS_ID, c.DOMAIN_ID, c.VOCABULARY_ID, c.VALID_START_DATE, c.VALID_END_DATE,
        r.RELATIONSHIP_NAME, 1 as RELATIONSHIP_DISTANCE
    FROM
        @CDM_schema.concept_relationship cr
    JOIN
        @CDM_schema.concept c ON cr.CONCEPT_ID_2 = c.CONCEPT_ID
    JOIN
        @CDM_schema.relationship r ON cr.RELATIONSHIP_ID = r.RELATIONSHIP_ID
    WHERE
        cr.CONCEPT_ID_1 IN (@conceptIdList)
        AND COALESCE(c.STANDARD_CONCEPT, 'N') IN ('S', 'C')
        AND cr.INVALID_REASON IS NULL
) c
GROUP BY
   c.CONCEPT_ID,
   c.CONCEPT_NAME,
   c.STANDARD_CONCEPT,
   c.INVALID_REASON,
   c.CONCEPT_CODE,
   c.CONCEPT_CLASS_ID,
   c.DOMAIN_ID,
   c.VOCABULARY_ID,
   c.VALID_START_DATE,
   c.VALID_END_DATE,
   c.RELATIONSHIP_NAME,
   c.RELATIONSHIP_DISTANCE
ORDER BY
   c.RELATIONSHIP_DISTANCE ASC;