SELECT CONCEPT_ID, CONCEPT_NAME, ISNULL(STANDARD_CONCEPT,'N') STANDARD_CONCEPT,
       ISNULL(INVALID_REASON,'V') INVALID_REASON, CONCEPT_CODE, CONCEPT_CLASS_ID,
       DOMAIN_ID, VOCABULARY_ID, VALID_START_DATE, VALID_END_DATE,
       'Descendant' RELATIONSHIP_NAME, MIN_LEVELS_OF_SEPARATION RELATIONSHIP_DISTANCE
FROM @vocabulary_database_schema.concept_ancestor ca
JOIN @vocabulary_database_schema.concept c ON c.CONCEPT_ID = ca.DESCENDANT_CONCEPT_ID
WHERE ANCESTOR_CONCEPT_ID = @id
