SELECT DISTINCT * FROM (
  SELECT c.CONCEPT_ID, CONCEPT_NAME, ISNULL(STANDARD_CONCEPT,'N') STANDARD_CONCEPT,
         ISNULL(c.INVALID_REASON,'V') INVALID_REASON, CONCEPT_CODE, CONCEPT_CLASS_ID,
         DOMAIN_ID, c.VOCABULARY_ID, c.VALID_START_DATE, c.VALID_END_DATE,
         RELATIONSHIP_NAME, 1 RELATIONSHIP_DISTANCE
  FROM @vocabulary_database_schema.concept_relationship cr
  JOIN @vocabulary_database_schema.concept c ON cr.CONCEPT_ID_2 = c.CONCEPT_ID
  JOIN @vocabulary_database_schema.relationship r ON cr.RELATIONSHIP_ID = r.RELATIONSHIP_ID
  WHERE cr.CONCEPT_ID_1 = @id AND cr.INVALID_REASON IS NULL
  UNION
  SELECT ANCESTOR_CONCEPT_ID, CONCEPT_NAME, ISNULL(STANDARD_CONCEPT,'N') STANDARD_CONCEPT,
         ISNULL(c.INVALID_REASON,'V') INVALID_REASON, CONCEPT_CODE, CONCEPT_CLASS_ID,
         DOMAIN_ID, c.VOCABULARY_ID, c.VALID_START_DATE, c.VALID_END_DATE,
         'Has ancestor of', MIN_LEVELS_OF_SEPARATION RELATIONSHIP_DISTANCE
  FROM @vocabulary_database_schema.concept_ancestor ca
  JOIN @vocabulary_database_schema.concept c ON c.CONCEPT_ID = ca.ANCESTOR_CONCEPT_ID
  WHERE DESCENDANT_CONCEPT_ID = @id AND ANCESTOR_CONCEPT_ID <> @id
  UNION
  SELECT DESCENDANT_CONCEPT_ID, CONCEPT_NAME, ISNULL(STANDARD_CONCEPT,'N') STANDARD_CONCEPT,
         ISNULL(c.INVALID_REASON,'V') INVALID_REASON, CONCEPT_CODE, CONCEPT_CLASS_ID,
         DOMAIN_ID, c.VOCABULARY_ID, c.VALID_START_DATE, c.VALID_END_DATE,
         'Has descendant of', MIN_LEVELS_OF_SEPARATION RELATIONSHIP_DISTANCE
  FROM @vocabulary_database_schema.concept_ancestor ca
  JOIN @vocabulary_database_schema.concept c ON c.CONCEPT_ID = ca.DESCENDANT_CONCEPT_ID
  WHERE ANCESTOR_CONCEPT_ID = @id AND DESCENDANT_CONCEPT_ID <> @id
) ALL_RELATED
ORDER BY RELATIONSHIP_DISTANCE ASC
