SELECT CONCEPT_ID, CONCEPT_NAME, ISNULL(STANDARD_CONCEPT,'N') STANDARD_CONCEPT,
       ISNULL(INVALID_REASON,'V') INVALID_REASON, CONCEPT_CODE, CONCEPT_CLASS_ID,
       DOMAIN_ID, VOCABULARY_ID, VALID_START_DATE, VALID_END_DATE
FROM @vocabulary_database_schema.concept
WHERE 1=1@filters
ORDER BY CONCEPT_NAME ASC
