CREATE TABLE SEC_USER (
    ID        SERIAL NOT NULL PRIMARY KEY,
    LOGIN     VARCHAR(50),
    PASSWORD  VARCHAR(255),
    SALT      VARCHAR(255),
    NAME      VARCHAR(100)
);

CREATE TABLE SEC_ROLE (
    ID        SERIAL NOT NULL PRIMARY KEY,
    NAME      VARCHAR(255)
);

CREATE TABLE SEC_USER_ROLE(
    USER_ID     SERIAL NOT NULL PRIMARY KEY,
    ROLE_ID     INT
);

CREATE TABLE SEC_PERMISSION(
    ID          SERIAL NOT NULL PRIMARY KEY,
    VALUE       VARCHAR(255) NOT NULL,
    ROLE_ID     INT NOT NULL
);
