CREATE SEQUENCE ${ohdsiSchema}.CONCEPT_SET_SNAPSHOT_METADATA_SEQUENCE MAXVALUE 9223372036854775807 NO CYCLE;

CREATE SEQUENCE ${ohdsiSchema}.CONCEPT_SET_ITEM_SNAPSHOTS_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9223372036854775807
    NO CYCLE;

CREATE SEQUENCE ${ohdsiSchema}.INCLUDED_CONCEPTS_SNAPSHOTS_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9223372036854775807
    NO CYCLE;

CREATE SEQUENCE ${ohdsiSchema}.INCLUDED_SOURCE_CODES_SNAPSHOTS_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9223372036854775807
    NO CYCLE;

CREATE TABLE ${ohdsiSchema}.CONCEPT_SET_SNAPSHOT_METADATA (
    ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('${ohdsiSchema}.CONCEPT_SET_SNAPSHOT_METADATA_SEQUENCE'),
    CONCEPT_SET_ID INTEGER NOT NULL,
    ACTION VARCHAR(10),
    LOCKED_DATE TIMESTAMP,
    LOCKED_BY VARCHAR(200),
    MESSAGE VARCHAR(2000),
    VOCABULARY_BUNDLE_NAME VARCHAR(200),
    VOCABULARY_BUNDLE_SCHEMA VARCHAR(200),
    VOCABULARY_BUNDLE_VERSION VARCHAR(200),
    CONCEPT_SET_VERSION VARCHAR(200)
);

CREATE TABLE ${ohdsiSchema}.CONCEPT_SET_ITEM_SNAPSHOTS (
    ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('${ohdsiSchema}.CONCEPT_SET_ITEM_SNAPSHOTS_SEQUENCE'),
    SNAPSHOT_METADATA_ID INTEGER NOT NULL,
    CONCEPT_ID INTEGER NOT NULL,
    CONCEPT_NAME VARCHAR(255) NOT NULL,
    DOMAIN_ID VARCHAR(20) NOT NULL,
    VOCABULARY_ID VARCHAR(20) NOT NULL,
    CONCEPT_CLASS_ID VARCHAR(20) NOT NULL,
    STANDARD_CONCEPT VARCHAR(1),
    CONCEPT_CODE VARCHAR(50) NOT NULL,
    VALID_START_DATE DATE NOT NULL,
    VALID_END_DATE DATE NOT NULL,
    INVALID_REASON VARCHAR(1),
    IS_EXCLUDED INTEGER NOT NULL,
    INCLUDE_DESCENDANTS INTEGER NOT NULL,
    INCLUDE_MAPPED INTEGER NOT NULL,
    FOREIGN KEY (SNAPSHOT_METADATA_ID) REFERENCES ${ohdsiSchema}.CONCEPT_SET_SNAPSHOT_METADATA(ID)
);

CREATE TABLE ${ohdsiSchema}.INCLUDED_CONCEPTS_SNAPSHOTS (
    ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('${ohdsiSchema}.INCLUDED_CONCEPTS_SNAPSHOTS_SEQUENCE'),
    SNAPSHOT_METADATA_ID INTEGER NOT NULL,
    CONCEPT_ID INTEGER NOT NULL,
    CONCEPT_NAME VARCHAR(255) NOT NULL,
    DOMAIN_ID VARCHAR(20) NOT NULL,
    VOCABULARY_ID VARCHAR(20) NOT NULL,
    CONCEPT_CLASS_ID VARCHAR(20) NOT NULL,
    STANDARD_CONCEPT VARCHAR(1),
    CONCEPT_CODE VARCHAR(50) NOT NULL,
    VALID_START_DATE DATE NOT NULL,
    VALID_END_DATE DATE NOT NULL,
    INVALID_REASON VARCHAR(1),
    FOREIGN KEY (SNAPSHOT_METADATA_ID) REFERENCES ${ohdsiSchema}.CONCEPT_SET_SNAPSHOT_METADATA(ID)
);

CREATE TABLE ${ohdsiSchema}.INCLUDED_SOURCE_CODES_SNAPSHOTS (
    ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('${ohdsiSchema}.INCLUDED_SOURCE_CODES_SNAPSHOTS_SEQUENCE'),
    SNAPSHOT_METADATA_ID INTEGER NOT NULL,
    CONCEPT_ID INTEGER NOT NULL,
    CONCEPT_NAME VARCHAR(255) NOT NULL,
    DOMAIN_ID VARCHAR(20) NOT NULL,
    VOCABULARY_ID VARCHAR(20) NOT NULL,
    CONCEPT_CLASS_ID VARCHAR(20) NOT NULL,
    STANDARD_CONCEPT VARCHAR(1),
    CONCEPT_CODE VARCHAR(50) NOT NULL,
    VALID_START_DATE DATE NOT NULL,
    VALID_END_DATE DATE NOT NULL,
    INVALID_REASON VARCHAR(1),
    FOREIGN KEY (SNAPSHOT_METADATA_ID) REFERENCES ${ohdsiSchema}.CONCEPT_SET_SNAPSHOT_METADATA(ID)
);