CREATE SEQUENCE ${ohdsiSchema}.CONCEPT_SET_COMPARE_JOB_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9223372036854775807
    NO CYCLE;
    
CREATE SEQUENCE ${ohdsiSchema}.CONCEPT_SET_COMPARE_JOB_DIFF_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9223372036854775807
    NO CYCLE;
        
CREATE TABLE ${ohdsiSchema}.CONCEPT_SET_COMPARE_JOB (
    ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('${ohdsiSchema}.CONCEPT_SET_COMPARE_JOB_SEQUENCE'),
    SOURCE_1_KEY VARCHAR(50) NOT NULL,
    SOURCE_2_KEY VARCHAR(50) NOT NULL,
    VOCAB_1_VERSION VARCHAR(255),
    VOCAB_2_VERSION VARCHAR(255),
    CREATED_FROM DATE,
    CREATED_TO DATE,
    UPDATED_FROM DATE,
    UPDATED_TO DATE,
    TAGS VARCHAR(5000),
    SKIP_LOCKED BOOLEAN NOT NULL
);

CREATE TABLE ${ohdsiSchema}.CONCEPT_SET_COMPARE_JOB_DIFF (
    ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('${ohdsiSchema}.CONCEPT_SET_COMPARE_JOB_DIFF_SEQUENCE'),
    COMPARE_JOB_ID INTEGER NOT NULL,
    CONCEPT_SET_ID INTEGER NOT NULL,
    CONCEPT_ID INTEGER NOT NULL,
    
    -- Concept Set membership counts
    CONCEPT_IN_CS1_ONLY BIGINT,
    CONCEPT_IN_CS2_ONLY BIGINT,
    CONCEPT_IN_CS1_AND_CS2 BIGINT,
    
    -- Concept names (only populated if name mismatch exists)
    VOCAB1_CONCEPT_NAME VARCHAR(1000),
    VOCAB2_CONCEPT_NAME VARCHAR(1000),
    
    NAME_MISMATCH BOOLEAN NOT NULL,
    
    FOREIGN KEY (COMPARE_JOB_ID) REFERENCES ${ohdsiSchema}.CONCEPT_SET_COMPARE_JOB(ID) ON DELETE CASCADE
);

-- Create indexes for better query performance
CREATE INDEX idx_cs_compare_job_diff_job_id ON ${ohdsiSchema}.CONCEPT_SET_COMPARE_JOB_DIFF(COMPARE_JOB_ID);
CREATE INDEX idx_cs_compare_job_diff_cs_id ON ${ohdsiSchema}.CONCEPT_SET_COMPARE_JOB_DIFF(CONCEPT_SET_ID);
CREATE INDEX idx_cs_compare_job_diff_concept_id ON ${ohdsiSchema}.CONCEPT_SET_COMPARE_JOB_DIFF(CONCEPT_ID);