-- WebAPI 3.0.0 Migration: Spring Batch 5 schema updates

-- Spring Batch 5 schema updates
DROP TABLE IF EXISTS ${ohdsiSchema}.BATCH_JOB_EXECUTION_PARAMS CASCADE;

CREATE TABLE ${ohdsiSchema}.BATCH_JOB_EXECUTION_PARAMS (
	JOB_EXECUTION_ID BIGINT NOT NULL,
	PARAMETER_NAME VARCHAR(100) NOT NULL,
	PARAMETER_TYPE VARCHAR(100) NOT NULL,
	PARAMETER_VALUE VARCHAR(2500),
	IDENTIFYING CHAR(1) NOT NULL,
	CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
	REFERENCES ${ohdsiSchema}.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE INDEX BJEP_JOB_EXEC_PARAMS_IDX ON ${ohdsiSchema}.BATCH_JOB_EXECUTION_PARAMS (JOB_EXECUTION_ID);

ALTER TABLE ${ohdsiSchema}.BATCH_STEP_EXECUTION
ADD COLUMN IF NOT EXISTS CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE ${ohdsiSchema}.BATCH_STEP_EXECUTION
ALTER COLUMN START_TIME DROP NOT NULL;
