SELECT DISTINCT 
	u2.SOURCE_ID,
	'DESCENDANT' AS MAPPING_TYPE, 
        u2.CONCEPT_ID_1 DRUG_CONCEPT_ID,
        c1.CONCEPT_NAME AS DRUG_CONCEPT_NAME,
	u2.CONCEPT_ID_2 AS CONDITION_CONCEPT_ID, 
	c2.CONCEPT_NAME AS CONDITION_CONCEPT_NAME,
	u2.UNIQUE_IDENTIFIER
FROM @cem_schema.NC_LU_CONCEPT_UNIVERSE u
    JOIN @cem_schema.concept_ancestor ca
            ON u.{@targetDomain=='CONDITION'}?{CONDITION_CONCEPT_ID}:{DRUG_CONCEPT_ID} = ca.ANCESTOR_CONCEPT_ID
{@targetDomain=='CONDITION'}?{
    JOIN @vocabularySchema.concept_ancestor ca2
        ON u.DRUG_CONCEPT_ID = ca2.ANCESTOR_CONCEPT_ID        
}
    JOIN @cem_schema.CEM_UNIFIED u2
            ON u2.{@targetDomain=='CONDITION'}?{CONCEPT_ID_2}:{CONCEPT_ID_1} = ca.DESCENDANT_CONCEPT_ID 
            AND u2.{@targetDomain=='CONDITION'}?{CONCEPT_ID_2}:{CONCEPT_ID_1} != ca.ANCESTOR_CONCEPT_ID 
            {@targetDomain=='CONDITION'}?{AND u2.CONCEPT_ID_1 = ca2.DESCENDANT_CONCEPT_ID}
    JOIN @vocabularySchema.concept c1
            ON c1.CONCEPT_ID = u2.CONCEPT_ID_1
    JOIN @vocabularySchema.concept c2
            ON c2.CONCEPT_ID = u2.CONCEPT_ID_2
WHERE u2.SOURCE_ID IN (@sourceIdList)
AND {@targetDomain=='CONDITION'}?{ca2.ANCESTOR_CONCEPT_ID}:{u2.CONCEPT_ID_1} IN (@drugList)
AND {@targetDomain=='CONDITION'}?{ca.ANCESTOR_CONCEPT_ID}:{u2.CONCEPT_ID_2} IN (@conditionList)
AND u2.CONCEPT_ID_2 != 0
AND u2.CONCEPT_ID_1 != 0

UNION ALL

SELECT DISTINCT 
	u2.SOURCE_ID,
	'EXACT' AS MAPPING_TYPE, 
        u2.CONCEPT_ID_1 AS DRUG_CONCEPT_ID,
        c1.CONCEPT_NAME AS DRUG_CONCEPT_NAME,
        u2.CONCEPT_ID_2 AS CONDITION_CONCEPT_ID,
	c2.CONCEPT_NAME AS CONDITION_CONCEPT_NAME,
	u2.UNIQUE_IDENTIFIER
FROM @cem_schema.CEM_UNIFIED u2
{@targetDomain=='CONDITION'}?{
    JOIN @vocabularySchema.concept_ancestor ca2
        ON u2.CONCEPT_ID_1 = ca2.DESCENDANT_CONCEPT_ID        
}
JOIN @vocabularySchema.concept c1
    ON c1.CONCEPT_ID = u2.CONCEPT_ID_1
JOIN @vocabularySchema.concept c2
    ON c2.CONCEPT_ID = u2.CONCEPT_ID_2
WHERE u2.SOURCE_ID IN (@sourceIdList)
AND {@targetDomain=='CONDITION'}?{ca2.ANCESTOR_CONCEPT_ID}:{u2.CONCEPT_ID_1} IN (@drugList)
AND u2.CONCEPT_ID_2 IN (@conditionList)
AND u2.CONCEPT_ID_2 != 0
AND u2.CONCEPT_ID_1 != 0

UNION ALL 

SELECT DISTINCT 
	u2.SOURCE_ID,
	'PARENT' AS MAPPING_TYPE, 
        u2.CONCEPT_ID_1 AS DRUG_CONCEPT_ID,
        c1.CONCEPT_NAME AS DRUG_CONCEPT_NAME,
	u2.CONCEPT_ID_2 AS CONDITION_CONCEPT_ID, 
	c2.CONCEPT_NAME AS CONDITION_CONCEPT_NAME,
	u2.UNIQUE_IDENTIFIER
FROM @cem_schema.NC_LU_CONCEPT_UNIVERSE u
    JOIN @vocabularySchema.concept_relationship cr
        ON u.{@targetDomain=='CONDITION'}?{CONDITION_CONCEPT_ID}:{DRUG_CONCEPT_ID} = cr.CONCEPT_ID_1
	{@targetDomain=='CONDITION'}?{AND UPPER(cr.relationship_id) = UPPER('IS A')}
    JOIN @cem_schema.CEM_UNIFIED u2
        ON u2.{@targetDomain=='CONDITION'}?{CONCEPT_ID_2}:{CONCEPT_ID_1} = cr.CONCEPT_ID_2
        AND u2.{@targetDomain=='CONDITION'}?{CONCEPT_ID_2}:{CONCEPT_ID_1} != cr.CONCEPT_ID_1
    JOIN @vocabularySchema.concept c1
	ON c1.CONCEPT_ID = u2.CONCEPT_ID_1
    JOIN @vocabularySchema.concept c2
	ON c2.CONCEPT_ID = u2.CONCEPT_ID_2
WHERE u2.SOURCE_ID IN (@sourceIdList)
AND u2.CONCEPT_ID_1 IN (@drugList)
AND {@targetDomain=='CONDITION'}?{cr.CONCEPT_ID_1}:{u2.CONCEPT_ID_2} IN (@conditionList)
AND u2.CONCEPT_ID_2 != 0
AND u2.CONCEPT_ID_1 != 0

UNION ALL

SELECT DISTINCT 
	SOURCE_ID,
	'ANCESTOR' AS MAPPING_TYPE, 
        u2.CONCEPT_ID_1 DRUG_CONCEPT_ID,
        c1.CONCEPT_NAME AS DRUG_CONCEPT_NAME,
	u2.CONCEPT_ID_2  AS CONDITION_CONCEPT_ID,
	c2.CONCEPT_NAME AS CONDITION_CONCEPT_NAME,
	u2.UNIQUE_IDENTIFIER
FROM @cem_schema.NC_LU_CONCEPT_UNIVERSE u
    JOIN @vocabularySchema.concept_ancestor ca
	ON u.{@targetDomain=='CONDITION'}?{CONDITION_CONCEPT_ID}:{DRUG_CONCEPT_ID} = ca.DESCENDANT_CONCEPT_ID
{@targetDomain=='CONDITION'}?{
    JOIN @vocabularySchema.concept_ancestor ca2
        ON u.DRUG_CONCEPT_ID = ca2.ANCESTOR_CONCEPT_ID        
}
    JOIN @cem_schema.CEM_UNIFIED u2
	ON u2.{@targetDomain=='CONDITION'}?{CONCEPT_ID_2}:{CONCEPT_ID_1} = ca.ANCESTOR_CONCEPT_ID
        {@targetDomain=='CONDITION'}?{AND u2.CONCEPT_ID_1 = ca2.DESCENDANT_CONCEPT_ID}
	AND u2.{@targetDomain=='CONDITION'}?{CONCEPT_ID_2}:{CONCEPT_ID_1} != ca.DESCENDANT_CONCEPT_ID
    JOIN @vocabularySchema.concept c1
	ON c1.CONCEPT_ID = u2.CONCEPT_ID_1
    JOIN @vocabularySchema.concept c2
	ON c2.CONCEPT_ID = u2.CONCEPT_ID_2
WHERE u2.SOURCE_ID IN (@sourceIdList)
AND {@targetDomain=='CONDITION'}?{ca2.ANCESTOR_CONCEPT_ID}:{u2.CONCEPT_ID_1} IN (@drugList)
AND {@targetDomain=='CONDITION'}?{ca.DESCENDANT_CONCEPT_ID}:{u2.CONCEPT_ID_2} IN (@conditionList)
AND u2.CONCEPT_ID_2 != 0
AND u2.CONCEPT_ID_1 != 0
;