SELECT DISTINCT 
	u2.SOURCE_ID,
	'DESCENDANT' AS MAPPING_TYPE, 
        u2.CONCEPT_ID_1 DRUG_CONCEPT_ID,
        c2.CONCEPT_NAME AS DRUG_CONCEPT_NAME,
	u.CONDITION_CONCEPT_ID, 
	c.CONCEPT_NAME AS CONDITION_CONCEPT_NAME,
	u2.UNIQUE_IDENTIFIER
FROM @evidenceSchema.NC_LU_CONCEPT_UNIVERSE u
	JOIN @evidenceSchema.CONCEPT_ANCESTOR ca
		ON u.{@targetDomain=='CONDITION'}?{CONDITION_CONCEPT_ID}:{DRUG_CONCEPT_ID} = ca.ANCESTOR_CONCEPT_ID
	JOIN @evidenceSchema.CEM_UNIFIED u2
		ON u2.CONCEPT_ID_2 = ca.DESCENDANT_CONCEPT_ID
		AND u2.CONCEPT_ID_2 != ca.ANCESTOR_CONCEPT_ID
		AND u2.SOURCE_ID IN (@sourceIdList)
	JOIN @vocabularySchema.CONCEPT c
		ON c.CONCEPT_ID = u.CONDITION_CONCEPT_ID
	JOIN @vocabularySchema.CONCEPT c2
		ON c2.CONCEPT_ID = u2.CONCEPT_ID_1
WHERE u2.CONCEPT_ID_1 IN (@drugList) -- Tofactinib
AND u2.CONCEPT_ID_2 IN (@conditionList) -- Anogenital herpesviral infection
AND u2.CONCEPT_ID_2 != 0
AND u2.CONCEPT_ID_1 != 0

UNION ALL

SELECT DISTINCT 
	u2.SOURCE_ID,
	'EXACT' AS MAPPING_TYPE, 
        u2.CONCEPT_ID_1 AS DRUG_CONCEPT_ID,
        c2.CONCEPT_NAME AS DRUG_CONCEPT_NAME,
        u2.CONCEPT_ID_2 AS CONDITION_CONCEPT_ID,
	c.CONCEPT_NAME AS CONDITION_CONCEPT_NAME,
	u2.UNIQUE_IDENTIFIER
FROM @evidenceSchema.CEM_UNIFIED u2
JOIN @vocabularySchema.CONCEPT c
	ON c.CONCEPT_ID = u2.CONCEPT_ID_2
	AND u2.SOURCE_ID IN (@sourceIdList)
JOIN @vocabularySchema.CONCEPT c2
	ON c2.CONCEPT_ID = u2.CONCEPT_ID_1
WHERE u2.CONCEPT_ID_1 IN (@drugList) -- Tofactinib
AND u2.CONCEPT_ID_2 IN (@conditionList) -- Anogenital herpesviral infection
AND u2.CONCEPT_ID_2 != 0
AND u2.CONCEPT_ID_1 != 0

UNION ALL 

SELECT DISTINCT 
	u2.SOURCE_ID,
	'PARENT' AS MAPPING_TYPE, 
        u2.CONCEPT_ID_1 AS DRUG_CONCEPT_ID,
        c2.CONCEPT_NAME AS DRUG_CONCEPT_NAME,
	u.CONDITION_CONCEPT_ID, 
	c.CONCEPT_NAME AS CONDITION_CONCEPT_NAME,
	u2.UNIQUE_IDENTIFIER
FROM @evidenceSchema.NC_LU_CONCEPT_UNIVERSE u
	JOIN @vocabularySchema.CONCEPT_RELATIONSHIP cr
		ON u.{@targetDomain=='CONDITION'}?{CONDITION_CONCEPT_ID}:{DRUG_CONCEPT_ID} = cr.CONCEPT_ID_2
		{@targetDomain=='CONDITION'}?{AND UPPER(cr.relationship_id) = UPPER('IS A')}
	JOIN @evidenceSchema.CEM_UNIFIED u2
		ON u2.CONCEPT_ID_2 = cr.CONCEPT_ID_2
		AND u2.CONCEPT_ID_2 != cr.CONCEPT_ID_1
		AND u2.SOURCE_ID IN (@sourceIdList)
	JOIN @vocabularySchema.CONCEPT c
		ON c.CONCEPT_ID = u.CONDITION_CONCEPT_ID
	JOIN @vocabularySchema.CONCEPT c2
		ON c2.CONCEPT_ID = u2.CONCEPT_ID_1
WHERE cr.CONCEPT_ID_1 IN (@conditionList) -- Anogenital herpesviral infection
AND u2.CONCEPT_ID_1 IN (@drugList) -- Tofactinib
AND u2.CONCEPT_ID_2 != 0
AND u2.CONCEPT_ID_1 != 0

UNION ALL

SELECT DISTINCT 
	SOURCE_ID,
	'ANCESTOR' AS MAPPING_TYPE, 
        u2.CONCEPT_ID_1 DRUG_CONCEPT_ID,
        c2.CONCEPT_NAME AS DRUG_CONCEPT_NAME,
	u.CONDITION_CONCEPT_ID,
	c.CONCEPT_NAME,
	u2.UNIQUE_IDENTIFIER
FROM @evidenceSchema.NC_LU_CONCEPT_UNIVERSE u
	JOIN @vocabularySchema.CONCEPT_ANCESTOR ca
		ON u.{@targetDomain=='CONDITION'}?{CONDITION_CONCEPT_ID}:{DRUG_CONCEPT_ID} = ca.DESCENDANT_CONCEPT_ID
	JOIN @evidenceSchema.CEM_UNIFIED u2
		ON u2.CONCEPT_ID_2 = ca.ANCESTOR_CONCEPT_ID
		AND u2.CONCEPT_ID_2 != ca.DESCENDANT_CONCEPT_ID
		AND u2.SOURCE_ID IN (@sourceIdList)
	JOIN @vocabularySchema.CONCEPT c
		ON c.CONCEPT_ID = u.CONDITION_CONCEPT_ID
	JOIN @vocabularySchema.CONCEPT c2
		ON c2.CONCEPT_ID = u2.CONCEPT_ID_1
WHERE ca.DESCENDANT_CONCEPT_ID IN (@conditionList) -- Anogenital herpesviral infection
AND u2.CONCEPT_ID_1 IN (@drugList) -- Tofactinib
AND u2.CONCEPT_ID_2 != 0
AND u2.CONCEPT_ID_1 != 0
;