SELECT EVIDENCE_TYPE, SUPPORTS, STATISTIC_VALUE, EVIDENCE_LINKOUT, STATISTIC_TYPE, DRUG DRUG_ID, RXNORM_DRUG DRUG_NAME, HOI CONDITION_ID, SNOMED_HOI CONDITION_NAME
FROM @tableQualifier.DRUG_HOI_EVIDENCE e
JOIN @tableQualifier.DRUG_HOI_RELATIONSHIP r 
on r.ID = e.DRUG_HOI_RELATIONSHIP
WHERE r.HOI = @id or r.DRUG = @id
