/*
SELECT 
	TITLE
, DESCRIPTION
, CONTRIBUTER
, CREATOR
, CREATION_DATE
, RIGHTS
, SOURCE
, COVERAGE_START_DATE
, COVERAGE_END_DATE
FROM @OHDSI_schema.EVIDENCE_SOURCES;
*/

SELECT 
	SOURCE_ID AS TITLE, 
	DESCRIPTION, 
	PROVENANCE,
	CONTRIBUTOR_ORGANIZATION AS CONTRIBUTOR,
	CONTACT_NAME,
	CREATION_DATE, 
	COVERAGE_START_DATE, 
	COVERAGE_END_DATE,
	VERSION_IDENTIFIER
FROM @cem_schema.SOURCE

