INSERT INTO @ohdsiSchema.CONCEPT_SET_NEGATIVE_CONTROLS
           (source_id
           ,concept_set_id
           ,concept_set_name
           ,concept_id
           ,concept_name
           ,domain_id
           ,MEDLINE_CT
           ,MEDLINE_CASE
           ,MEDLINE_OTHER
           ,SEMMEDDB_CT_T
           ,SEMMEDDB_CASE_T
           ,SEMMEDDB_OTHER_T
           ,SEMMEDDB_CT_F
           ,SEMMEDDB_CASE_F
           ,SEMMEDDB_OTHER_F
           ,EU_SPC
           ,SPL_ADR
           ,AERS
           ,AERS_PRR
           ,MEDLINE_CT_SCALED
           ,MEDLINE_CASE_SCALED
           ,MEDLINE_OTHER_SCALED
           ,SEMMEDDB_CT_T_SCALED
           ,SEMMEDDB_CASE_T_SCALED
           ,SEMMEDDB_OTHER_T_SCALED
           ,SEMMEDDB_CT_F_SCALED
           ,SEMMEDDB_CASE_F_SCALED
           ,SEMMEDDB_OTHER_F_SCALED
           ,EU_SPC_SCALED
           ,SPL_ADR_SCALED
           ,AERS_SCALED
           ,AERS_PRR_SCALED
           ,MEDLINE_CT_BETA
           ,MEDLINE_CASE_BETA
           ,MEDLINE_OTHER_BETA
           ,SEMMEDDB_CT_T_BETA
           ,SEMMEDDB_CASE_T_BETA
           ,SEMMEDDB_OTHER_T_BETA
           ,SEMMEDDB_CT_F_BETA
           ,SEMMEDDB_CASE_F_BETA
           ,SEMMEDDB_OTHER_F_BETA
           ,EU_SPC_BETA
           ,SPL_ADR_BETA
           ,AERS_BETA
           ,AERS_PRR_BETA
           ,RAW_Prediction
           ,PREDICTION)
     VALUES
           (?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
)
