IF OBJECT_ID('tempdb..#TEMP_1', 'U') IS NOT NULL DROP TABLE #TEMP_1;
IF OBJECT_ID('tempdb..#TEMP_2', 'U') IS NOT NULL DROP TABLE #TEMP_2;
IF OBJECT_ID('tempdb..#TEMP_3', 'U') IS NOT NULL DROP TABLE #TEMP_3;
IF OBJECT_ID('tempdb..#TEMP_4', 'U') IS NOT NULL DROP TABLE #TEMP_4;
IF OBJECT_ID('tempdb..#TEMP_5', 'U') IS NOT NULL DROP TABLE #TEMP_5;

/*PMID DESCENDANT COUNT*/
SELECT DATA_TYPE,
  u.CONCEPT_ID AS OUTCOME_OF_INTEREST_CONCEPT_ID,
	u.CONCEPT_NAME AS OUTCOME_OF_INTEREST_CONCEPT_NAME,
	COUNT(DISTINCT descendant.UNIQUE_IDENTIFIER) AS DESCENDANT_COUNT
INTO #TEMP_1
FROM #NC_CONCEPT_UNIVERSE u
	LEFT OUTER JOIN #NC_ADE_SUMMARY descendant
		ON descendant.OUTCOME_OF_INTEREST_CONCEPT_ID = u.CONCEPT_ID
		AND descendant.MAPPING_TYPE = 'DESCENDANT'
GROUP BY DATA_TYPE,u.CONCEPT_ID, u.CONCEPT_NAME;

/*PMID EXACT COUNT*/
SELECT DATA_TYPE,
  u.CONCEPT_ID AS OUTCOME_OF_INTEREST_CONCEPT_ID,
	COUNT(DISTINCT exact.UNIQUE_IDENTIFIER) AS EXACT_COUNT
INTO #TEMP_2
FROM #NC_CONCEPT_UNIVERSE u
  LEFT OUTER JOIN #NC_ADE_SUMMARY exact
		ON exact.OUTCOME_OF_INTEREST_CONCEPT_ID = u.CONCEPT_ID
		AND exact.MAPPING_TYPE = 'EXACT'
GROUP BY DATA_TYPE,u.CONCEPT_ID;

/*PMID PARENT COUNT*/
SELECT DATA_TYPE,
  u.CONCEPT_ID AS OUTCOME_OF_INTEREST_CONCEPT_ID,
	COUNT(DISTINCT parent.UNIQUE_IDENTIFIER) AS PARENT_COUNT
INTO #TEMP_3
FROM #NC_CONCEPT_UNIVERSE u
	LEFT OUTER JOIN #NC_ADE_SUMMARY parent
		ON parent.OUTCOME_OF_INTEREST_CONCEPT_ID = u.CONCEPT_ID
		AND parent.MAPPING_TYPE = 'PARENT'
GROUP BY DATA_TYPE,u.CONCEPT_ID;

/*PMID ANCESTOR COUNT*/
SELECT DATA_TYPE,
  u.CONCEPT_ID AS OUTCOME_OF_INTEREST_CONCEPT_ID,
	COUNT(DISTINCT ancestor.UNIQUE_IDENTIFIER) AS ANCESTOR_COUNT
INTO #TEMP_4
FROM #NC_CONCEPT_UNIVERSE u
	LEFT OUTER JOIN #NC_ADE_SUMMARY ancestor
		ON ancestor.OUTCOME_OF_INTEREST_CONCEPT_ID = u.CONCEPT_ID
		AND ancestor.MAPPING_TYPE = 'ANCESTOR'
GROUP BY DATA_TYPE,u.CONCEPT_ID;



SELECT u.CONCEPT_ID AS OUTCOME_OF_INTEREST_CONCEPT_ID,
	MAX(CASE WHEN i.CONCEPT_ID IS NULL THEN 0 ELSE 1 END) AS IND_CI,
	MAX(CASE WHEN tb.CONCEPT_ID IS NULL THEN 0 ELSE 1 END) AS TOO_BROAD,
	MAX(CASE WHEN di.CONCEPT_ID IS NULL THEN 0 ELSE 1 END) AS DRUG_INDUCED,
	{@outcomeOfInterest == 'condition'}?{MAX(CASE WHEN p.CONCEPT_ID IS NULL THEN 0 ELSE 1 END) } : {0} AS PREGNANCY,
	MAX(CASE WHEN ue.CONCEPT_ID IS NULL THEN 0 ELSE 1 END) AS USER_EXCLUDED,
	MAX(CASE WHEN ui.CONCEPT_ID IS NULL THEN 0 ELSE 1 END) AS USER_INCLUDED
INTO #TEMP_5
FROM #NC_CONCEPT_UNIVERSE u
	LEFT OUTER JOIN #NC_INDICATIONS i
		ON i.CONCEPT_ID = u.CONCEPT_ID
	LEFT OUTER JOIN @broadConceptsData  tb
  		ON tb.CONCEPT_ID = u.CONCEPT_ID
	LEFT OUTER JOIN @drugInducedConditionsData di
		ON di.CONCEPT_ID = u.CONCEPT_ID

	{@outcomeOfInterest == 'condition'}?{
  	LEFT OUTER JOIN @pregnancyConditionData p
  		ON p.CONCEPT_ID = u.CONCEPT_ID
  }

	LEFT OUTER JOIN @conceptsToExclude ue
		ON ue.CONCEPT_ID = u.CONCEPT_ID
	LEFT OUTER JOIN @conceptsToInclude ui
		ON ui.CONCEPT_ID = u.CONCEPT_ID
GROUP BY u.CONCEPT_ID;



/*PULL TOGETHER*/
SELECT u.CONCEPT_ID AS OUTCOME_OF_INTEREST_CONCEPT_ID,
	u.CONCEPT_NAME AS OUTCOME_OF_INTEREST_CONCEPT_NAME,
  ROW_NUMBER() OVER(ORDER BY u.SORT_ORDER) AS SORT_ORDER,
  MAX(CASE WHEN t1.DATA_TYPE = 'MEDLINE_WINNENBURG' THEN t1.DESCENDANT_COUNT ELSE 0 END)  AS DESCENDANT_PMID_COUNT,
  MAX(CASE WHEN t2.DATA_TYPE = 'MEDLINE_WINNENBURG' THEN t2.EXACT_COUNT ELSE 0 END)      AS EXACT_PMID_COUNT,
  MAX(CASE WHEN t3.DATA_TYPE = 'MEDLINE_WINNENBURG' THEN t3.PARENT_COUNT ELSE 0 END)      AS PARENT_PMID_COUNT,
  MAX(CASE WHEN t4.DATA_TYPE = 'MEDLINE_WINNENBURG' THEN t4.ANCESTOR_COUNT ELSE 0 END)    AS ANCESTOR_PMID_COUNT,
  t5.IND_CI,
  t5.TOO_BROAD,
  t5.DRUG_INDUCED,
  t5.PREGNANCY,
  MAX(CASE WHEN t1.DATA_TYPE = 'SPLICER' THEN 1 ELSE 0 END)  AS DESCENDANT_SPLICER,
  MAX(CASE WHEN t2.DATA_TYPE = 'SPLICER' THEN 1 ELSE 0 END)  AS EXACT_SPLICER,
  MAX(CASE WHEN t3.DATA_TYPE = 'SPLICER' THEN 1 ELSE 0 END)  AS PARENT_SPLICER,
  MAX(CASE WHEN t4.DATA_TYPE = 'SPLICER' THEN 1 ELSE 0 END)  AS ANCESTOR_SPLICER,
  MAX(CASE WHEN t1.DATA_TYPE = 'AEOLUS' THEN 1 ELSE 0 END)  AS DESCENDANT_FAERS,
  MAX(CASE WHEN t2.DATA_TYPE = 'AEOLUS' THEN 1 ELSE 0 END)  AS EXACT_FAERS,
  MAX(CASE WHEN t3.DATA_TYPE = 'AEOLUS' THEN 1 ELSE 0 END)  AS PARENT_FAERS,
  MAX(CASE WHEN t4.DATA_TYPE = 'AEOLUS' THEN 1 ELSE 0 END)  AS ANCESTOR_FAERS,
  t5.USER_EXCLUDED,
  t5.USER_INCLUDED
INTO #NC_SUMMARY
FROM #NC_CONCEPT_UNIVERSE u
  JOIN #TEMP_1 t1
    ON u.CONCEPT_ID = t1.OUTCOME_OF_INTEREST_CONCEPT_ID
  JOIN #TEMP_2 t2
    ON u.CONCEPT_ID = t2.OUTCOME_OF_INTEREST_CONCEPT_ID
  JOIN #TEMP_3 t3
    ON u.CONCEPT_ID = t3.OUTCOME_OF_INTEREST_CONCEPT_ID
  JOIN #TEMP_4 t4
    ON u.CONCEPT_ID = t4.OUTCOME_OF_INTEREST_CONCEPT_ID
  JOIN #TEMP_5 t5
    ON u.CONCEPT_ID = t5.OUTCOME_OF_INTEREST_CONCEPT_ID
GROUP BY u.CONCEPT_ID, u.CONCEPT_NAME, u.SORT_ORDER,
  t5.IND_CI,
  t5.TOO_BROAD,
  t5.DRUG_INDUCED,
  t5.PREGNANCY,
  t5.USER_EXCLUDED,
  t5.USER_INCLUDED;


