 select E.JOB_EXECUTION_ID, E.START_TIME, E.END_TIME, E.STATUS, E.EXIT_CODE, E.EXIT_MESSAGE, E.CREATE_TIME, E.LAST_UPDATED, E.VERSION, 
        I.JOB_INSTANCE_ID, I.JOB_NAME, P.JOB_EXECUTION_ID, P.PARAMETER_NAME, P.PARAMETER_TYPE, P.PARAMETER_VALUE, P.IDENTIFYING 
 from @ohdsi_schema.BATCH_JOB_EXECUTION E
 join @ohdsi_schema.BATCH_JOB_INSTANCE I on I.JOB_INSTANCE_ID = E.JOB_INSTANCE_ID
 left outer join @ohdsi_schema.BATCH_JOB_EXECUTION_PARAMS P on P.JOB_EXECUTION_ID = E.JOB_EXECUTION_ID
 order by E.JOB_EXECUTION_ID DESC