SELECT
    CONCEPT_ID_1
     , c1.CONCEPT_NAME AS CONCEPT_ID_1_NAME
     , CONCEPT_ID_2
     , c2.CONCEPT_NAME AS CONCEPT_ID_2_NAME
     , SOURCE_ID
     , EVIDENCE_TYPE
     , RELATIONSHIP_ID
     , UNIQUE_IDENTIFIER
     , UNIQUE_IDENTIFIER_TYPE
     ,	STATISTIC_VALUE
     , STATISTIC_VALUE_TYPE
FROM evidence_schema.CEM_UNIFIED u
         JOIN evidence_schema.concept c1
              ON c1.CONCEPT_ID = u.CONCEPT_ID_1
         JOIN evidence_schema.concept c2
              ON c2.CONCEPT_ID = u.CONCEPT_ID_2
WHERE (CONCEPT_ID_1 = ? OR CONCEPT_ID_1 = ?)
  AND (CONCEPT_ID_2 = ? OR CONCEPT_ID_2 = ?)